### ISSUE TITLE
wrong URL under OPenDAP page

### ISSUE THREAD

**Issue by saveriogzz** [Unidata/tds#122]
Hello,

I'm running Thredds 5.0.0-beta5 on a docker container, using apache2 as a reverse proxy. You can find the service at [this address](https://ruisdael.citg.tudelft.nl/thredds/catalog/testAll/catalog.html).
As you can see under the [OPenDAP page](https://ruisdael.citg.tudelft.nl/thredds/dodsC/testAll/PHWUR_202009141117.nc.html) for one of the files, the Data URL seems to be the one internal to the docker container. How can I fix this?

Thanks!

**Comment by lesserwhirls** [comment]
Greetings @saveriogzz! If you are seeing the internal URL, this is an indication that the proxy isn't fully configured. We have some documentation about configuring a reverse proxy with apache and tomcat:

https://docs.unidata.ucar.edu/tds/5.0/userguide/tds_behind_proxy.html#using-tomcat-and-apache-http-server

but I believe there are a few ways of doing it.

**Comment by saveriogzz** [comment]
Thank you @lesserwhirls ! I'll close this then :)
All the best and thank you for the efforts on building this!
