### ISSUE TITLE
Applying styles to WMS with SLD

### ISSUE THREAD

**Issue by zdefne-usgs** [Unidata/tds#126]
There was a recent update TDS WMS configuration to support SLD parameter #73. I would like to use this feature but it is not clear how it can be used. 

Can someone (@ethanrd ?)  help/point to any resources about using a SLD to define the style of a WMS on TDS? 

I assume it is not as simple as copying an SLD with the same name as the WMS/.nc file? 🤔

**Comment by ethanrd** [comment]
Hi @zdefne-usgs - Are you interested in adding SLD configuration files to a TDS so more styles are available from WMS? Or are you interested in supporting user supplied SLD?

For server configuration, I believe the underlying ncWMS code [supports SLD](https://reading-escience-centre.gitbooks.io/ncwms-user-guide/content/06-development.html#styles) configuration files. I would have to double check if that works in the TDS. (@lesserwhirls - do you know?)

Issue #73 fixed an issue with the TDS rejecting a user WMS GET request coming in with a `SLD_BODY` parameter. Basically, a URL parameter containing a flattened, %-encoded SLD/XML document. There is an example of that in the TestWmsServer file [here](https://github.com/Unidata/tds/blob/987a79bf15192c52cc3fc815273f36fed9a93fc4/it/src/test/java/thredds/server/wms/TestWmsServer.java#L88).
