### ISSUE TITLE
Discuss tds.content.root.path/thredds/public 

### ISSUE THREAD

**Issue by oxelson** [Unidata/tds#128]
Discuss the tds.content.root.path/thredds/public directory and it's contents/purpose.  Is there a need for it in light of the TDS5's used of Thymeleaf?

**Comment by haileyajohnson** [comment]
Apparently we put user-supplied stylesheets there [see here](https://docs.unidata.ucar.edu/tds/5.0/userguide/customizing_tds_look_and_feel.html#css-stylesheets) but I don't think we have to be locked in to that. It looks like Thymeleaf fragments and Jupyter notebooks go in their own directories in the content folder.

**Comment by oxelson** [comment]
I'm updating the docs for TDS5 and was wondering if the CSS stuff should go in the templates directory with the thymeleaf frags?  According to @lesserwhirls, here is what is allowed in the directory:  

"*.css", "*.gif", "*.jpg", "*.png", "*.jsp", "sitemap.xml"

The sitemap.xml is a good idea.  We also should include a place to stash robots.txt.

Should the images go in the templates directory too? 

Just trying to see if this is still needed and what we should say about it in the docs.

**Comment by haileyajohnson** [comment]
I think that sounds reasonable, but "templates" is pretty thymeleaf specific, so maybe we should rename that directory if we're gonna put more stuff in there?

**Comment by oxelson** [comment]
I'm OK keeping them separate if you are.  I wanted to pick your brain to see what you and @lesserwhirls though about this topic.
