### ISSUE TITLE
How to configure the WMS for 5.0?

### ISSUE THREAD

**Issue by Chilipp** [Unidata/tds#142]
Hey dear TDS developers!

we are running a THREDDS-Server using `unidata/thredds-docker:5.0-beta8` and would like to use the wms functionalities there. However, as I understood from https://github.com/Unidata/thredds/issues/909 (and confirmed myself via manipulating the wmsConfig.xml file), the docs for 5.0 on configuring the wms are outdated here. Do you have any starting point where I can learn how to configure the WMS, e.g. how to change the default style for specific variables and where this config has to be placed?

Thanks for your support!

**Comment by lesserwhirls** [comment]
Greetings @Chilipp! The functionality for using `wmsConfig.xml` is still not available in `5.x`, but, I will be making a PR today that addresses that (currently running our test suite to make sure nothing else broke). Stay tuned!

**Comment by Chilipp** [comment]
Awesome! Thanks a lot @lesserwhirls highly looking forward to it :smiley:
