### ISSUE TITLE
NCSS validation errors

### ISSUE THREAD

**Issue by haileyajohnson** [Unidata/tds#158]
TDSv5.x

- time parameter should be optional
- Grid as point is not working - throws NullPointerException
- request validation should inform user if request parameters are outside dataset (currently returns file not found error)

**Comment by lesserwhirls** [comment]
NCSS Grid as Point should be working. Where are you seeing the failure? The HTML form is broken on thredds-test, thredds-dev, but that's due to security changes that end up blocking some JavaScript stuff (I think).

**Comment by haileyajohnson** [comment]
This was in response to an eSupport ticket - if it's fixed I can go ahead and close this and tell them to use the 5 release?
