### ISSUE TITLE
can't set "content-type" for JSON files (and others)

### ISSUE THREAD

**Issue by wwlwpd** [Unidata/tds#161]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue

4.6+, 5

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)

5.0 docker container on the latest LTS Ubuntu

* a description of the issue with the steps needed to reproduce it

Can't get content-type righ in config:

Seems it hard code here?

tdcommon/src/main/java/thredds/util/ContentType.java

**Comment by haileyajohnson** [comment]
@wwlwpd Could you provide some clarification on your linked issue: I see that JSON files on [this TDS](https://fortytwo.cct.lsu.edu/thredds) open in browser, however [here](http://chg-1.oden.tacc.utexas.edu/thredd) they download. Was this also the behavior before the TDS was upgraded to 5? Before it was upgraded, were the two servers using the same version?

**Comment by oxelson** [comment]
I can confirm the TDS 5.0 out-of-the box assigns the Content-type of octet-stream to JSON files.  

Manipulation of the TDS deployment descriptor (web.xml) file in the hope of overriding the content-type was unsuccessful.

I also tried to see what level of control I have if I proxy to the TDS from an HTTP server (I tried both apache and nginx) hoping maybe I could change the content-type header after Tomcat hands the response back to the web server but before it goes to the client.  No luck with this ether, as I can't find a way to intercept the returning response from Tomcat.

**Comment by wwlwpd** [comment]
> @wwlwpd Could you provide some clarification on your linked issue: I see that JSON files on [this TDS](https://fortytwo.cct.lsu.edu/thredds) open in browser, however [here](http://chg-1.oden.tacc.utexas.edu/thredd) they download. Was this also the behavior before the TDS was upgraded to 5? Before it was upgraded, were the two servers using the same version?

The link above has never properly set `content-type`, started with 4.6. It's now 5.0.

We did have a set up running 3.7 that _did_ work out of the box for `.json`.

**Comment by ethanrd** [comment]
Hi @wwlwpd - I have a fix that will default to querying the server for well known and server configured content types. Just cleaning up some new tests and then I'll get a PR submitted.
