### ISSUE TITLE
Issues with NCSS under TDS5

### ISSUE THREAD

**Issue by manoch-iris** [Unidata/tds#189]
Under TDS4 and TDS5, trying NCSS with a NetCDF file that uses two-dimensional coordinate variables, as described by the [CF conventions](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_two_dimensional_latitude_longitude_coordinate_variables), produces two different responses:

Under TDS4.latest, all is well, and I can extract values from the file:

<img width="1183" alt="TDS_4" src="https://user-images.githubusercontent.com/5756394/149413118-3ba8d10a-ac6d-46e6-95b3-9eb6cc8e18a3.png">

Under TDS5 SNAPSHOT-5.4: I run into the following problems (some are the same as #169):
- Map of the horizontal extent is wrong
- It is asking for time, while time is supposed to be optional

<img width="1185" alt="TDS_5" src="https://user-images.githubusercontent.com/5756394/149413147-edaef9db-0347-4a96-9249-89f5a41b083d.png">

- Can display variables correctly, but when using the same
  limits as I used with TDS4, it throws InvalidRangeException

<img width="1187" alt="Error_range" src="https://user-images.githubusercontent.com/5756394/149412330-086d0dfb-71d5-4948-aa2e-985f77ea9ece.png">

- When changing the horizontal extent to full extension, I receive the "Dimension y does not exist error."

<img width="1189" alt="Error_y" src="https://user-images.githubusercontent.com/5756394/149412416-ebff0a7f-fe79-4083-a9f7-44ccf38fcba2.png">

**Comment by haileyajohnson** [comment]
@manoch-iris do you have a sample file you could share to reproduce these issues?

**Comment by manoch-iris** [comment]
Hi Hailey,

Thanks for looking into this. You can find the same test file that I used here:

https://ds.iris.edu/files/staff/manoch/emc/tds/ <https://ds.iris.edu/files/staff/manoch/emc/tds/>

Cheers,

—manoch

**Comment by haileyajohnson** [comment]
Great, thanks. As an update, I've finally managed to look into the issues you reported via the support mailing list, and should have those fixes merged shortly. Thanks for your patience, I know it's been a slow process.

**Comment by haileyajohnson** [comment]
Fixed in [netcdf-java #986](https://github.com/Unidata/netcdf-java/pull/986) and #218 (as well a few other related PRs)
