### ISSUE TITLE
Nested aggregation fails with NPE in 5.4 SNAPSHOT. Worked correctly in 4.6.20.

### ISSUE THREAD

**Issue by noaaroland** [Unidata/tds#225]
This concerns TDS 5.4-SNAPSHOT 

Implementation-Title: THREDDS Data Server (TDS)
Implementation-Version: 5.4-SNAPSHOT

Running on Red Hat Enterprise Linux Workstation release 6.10 (Santiago)
with 
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode)

The attached catalog (called test_B10k.txt for github upload reasons) worked correctly with:
Implementation-Title: THREDDS Data Server (TDS)
Implementation-Version: 4.6.20

But, the nested aggregation fails with 5.4.

```
2022-05-19T16:00:24.463 +0000 [     71600][       5] ERROR - thredds.server.opendap.OpendapServlet - request= ReqState:
  serverClassName:    'null'
  dataSet:            'B10K-H16_CMIP5_Level1_CESM_BIO_rcp85_collection.nc'
  requestSuffix:      'html'
  CE:                 ''
  compressOK:          true
  InitParameters:

java.lang.NullPointerException: null
        at thredds.inventory.MFileProvider.canProvide(MFileProvider.java:21) ~[cdm-core-5.5.3-SNAPSHOT.jar:5.5.3-SNAPSHOT]
```

You can download the files in order to test from these links:

https://data.pmel.noaa.gov/aclim/thredds/fileServer/B10K-H16_CMIP5_CESM_BIO_rcp85/Level1/2005-2009/B10K-H16_CMIP5_CESM_BIO_rcp85_2005-2009_average_aice.nc
https://data.pmel.noaa.gov/aclim/thredds/fileServer/B10K-H16_CMIP5_CESM_BIO_rcp85/Level1/2010-2014/B10K-H16_CMIP5_CESM_BIO_rcp85_2010-2014_average_aice.nc
https://data.pmel.noaa.gov/aclim/thredds/fileServer/B10K-H16_CMIP5_CESM_BIO_rcp85/Level1/2015-2019/B10K-H16_CMIP5_CESM_BIO_rcp85_2015-2019_average_aice.nc

https://data.pmel.noaa.gov/aclim/thredds/fileServer/B10K-H16_CMIP5_CESM_BIO_rcp85/Level1/2005-2009/B10K-H16_CMIP5_CESM_BIO_rcp85_2005-2009_average_Ben.nc
https://data.pmel.noaa.gov/aclim/thredds/fileServer/B10K-H16_CMIP5_CESM_BIO_rcp85/Level1/2010-2014/B10K-H16_CMIP5_CESM_BIO_rcp85_2010-2014_average_Ben.nc
https://data.pmel.noaa.gov/aclim/thredds/fileServer/B10K-H16_CMIP5_CESM_BIO_rcp85/Level1/2015-2019/B10K-H16_CMIP5_CESM_BIO_rcp85_2015-2019_average_Ben.nc

[test_B10k.txt](https://github.com/Unidata/tds/files/8732275/test_B10k.txt)

**Comment by tdrwenski** [comment]
Hi Roland, thanks for bring this to our attention! I have reproduced this bug and am looking into a fix.

**Comment by tdrwenski** [comment]
Hi Roland, the fix for this bug was merged. We hope to be releasing 5.4 in the coming weeks, and that release will include this fix.
