### ISSUE TITLE
HTTP Access of CDMS3 objects?

### ISSUE THREAD

**Issue by dblodgett-usgs** [Unidata/tds#227]
* `unidata/thredds-docker:5.3`
* I have some objects that I want to make available in whole via http - I get a 404 when trying a link that should otherwise work.

**Comment by tdrwenski** [comment]
Hi, thanks for reporting this. We actually have already fixed this bug and it is in the latest 5.4-snapshot war file, but unfortunately the fix is not yet in a docker release. We hope to have version 5.4 released in the coming weeks, and the docker image we release then should include the fix.

**Comment by dblodgett-usgs** [comment]
Great. Thank you! I'll carry on and look forward to the fix.
