### ISSUE TITLE
"Send trigger" links in the admin/debug interface should use 'test' not 'nocheck'

### ISSUE THREAD

**Issue by rjdave** [Unidata/tds#231]
THREDDS-5.4-SNAPSHOT from 05-13-2022
CentOS 7, AdoptOpenJDK 11.0.15+10, Tomcat 8.5.75

When using the `admin/debug` interface and navigating to the `admin/collection/showCollection` page for a given dataset, there is a "Send trigger to _datasetName_" link. However, since the trigger action is set to `nocheck`, this trigger is only effective if there is currently no collection index for that dataset. This is virtually impossible since every option for update, except maybe `never`, would have built the initial index on server startup. The link cannot be used to update a dataset that you have recently added files to.

Currently the link's target is something like:

`https://host/thredds/admin/collection/trigger?collection=name&trigger=nocheck`

I believe is should be more like (`test` instead of `nocheck`):

`https://host/thredds/admin/collection/trigger?collection=name&trigger=test`

I have confirmed that if I start an FMRC, add files, then use the trigger in its existing form (`nocheck`), the FMRC dataset does **NOT** update. However, if I replace `nocheck` with `test`, the dataset updates.

**Comment by rjdave** [comment]
THREDDS-5.5-SNAPSHOT from 07-26-2022
CentOS 7, AdoptOpenJDK 11.0.15+10, Tomcat 8.5.75

I tested the latest snapshot and I get the same results (still `trigger=nocheck` and dataset is not updated).

I believe the only change needed would be in `tds/src/main/java/thredds/server/admin/AdminCollectionController.java` at line 174 changing `nocheck` to `test`. However, I was unable to find the where `CollectionUpdateType` is created. All I can tell is that it's imported from `thredds.inventory`. I couldn't find the code for package `thredds.inventory` in the TDS source code.

**Comment by tdrwenski** [comment]
I think some users wanted to have "trigger=nocheck" when they had collections generated outside of TDS. 

Maybe you can just curl the url you want with "trigger=test"? Or if you prefer the link on the admin page, we can add a "trigger=test" link next to the "trigger=nocheck" one.

**Comment by rjdave** [comment]
We use wget with "trigger=test" in our scripts to send the triggers automatically each time new data is generated/processed. I only use the admin interface when I'm testing a dataset, but having a link for "trigger=test" would be convenient.

> I think some users wanted to have "trigger=nocheck" when they had collections generated outside of TDS.

Do you mean grib collections using the TDM or is there an offline way to generate gridded NetCDF FMRC collections?

**Comment by tdrwenski** [comment]
I was told some users had a script to generate FMRC collections similar to how the TDM generates grib feature collection indexes, but I actually don't know how that worked or if that still works in TDS 5.

I anyhow just went with adding the "trigger=test" option next to the "trigger=nocheck" option, you should see that in the newest snapshot:

https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/edu/ucar/tds/5.5-SNAPSHOT/tds-5.5-20220809.202414-26.war

**Comment by rjdave** [comment]
Thanks, that looks great!
