### ISSUE TITLE
IOSP Implementation works with Java netCDF directly, but not when plugged into TDS.

### ISSUE THREAD

**Issue by noaaroland** [Unidata/tds#255]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue

Implementation-Title: THREDDS Data Server (TDS)
Implementation-Version: 5.4

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)

Red Hat Enterprise Linux Workstation release 6.10 (Santiago)

openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode)

Java netCDF 5.5.3

* a description of the issue:

An IOSP implementation works with:

```
NetcdfFiles.registerIOProvider("sdig.ftds.iosp.FerretIOServiceProvider");
NetcdfFile my_file = NetcdfFiles.open("src/test/java/sdig/ftds/iosp/coads_avg.jnl", null);
...
Variable avg = my_file.findVariable("sst_avg");
...
Array a = avg.read(ranges);
assertEquals(a.getFloat(0), 28.4456310, .01);
```

But fails when attempting to access data when the IOSP is plugged into TDS 5.4 with:

```
  <nj22Config>
    <ioServiceProvider class="sdig.ftds.iosp.FerretIOServiceProvider"/>
  </nj22Config>
```

The initial request for coads.jnl.hmtl?null works fine. The DEBUG output shows the correct ISOP being called to build the header and the HTML interface shows in the browser with the virtual variable (sst_avg) displayed with the correct dimensions.

But the call to  coads_avg.jnl.ascii?sst_avg[40:1:50][30:1:40] fails with a java.lang.IllegalArgumentException so the readSection never gets called.

```
2022-07-26T20:26:05.507 +0000 [    128787][       7] DEBUG - thredds.server.opendap.OpendapServlet - OpendapServlet: nom
inal url: https://dunkel.pmel.noaa.gov:8940/thredds/dodsC/pile/coads_avg.jnl.html?null
2022-07-26T20:26:05.507 +0000 [    128787][       7] DEBUG - thredds.core.DatasetManager - DatasetHandler wants pile/coa
ds_avg.jnl
2022-07-26T20:26:05.579 +0000 [    128859][       7] DEBUG - ucar.nc2.NetcdfFile - Using IOSP sdig.ftds.iosp.FerretIOSer
viceProvider
2022-07-26T20:26:05.606 +0000 [    128886][       7] DEBUG - thredds.server.opendap.NcDDS -  NcDDS adding coordinate var
iable COADSX for dimension COADSX
2022-07-26T20:26:05.606 +0000 [    128886][       7] DEBUG - thredds.server.opendap.NcDDS -  NcDDS adding coordinate var
iable COADSY for dimension COADSY
2022-07-26T20:26:05.606 +0000 [    128886][       7] DEBUG - thredds.server.opendap.NcDDS -  NcDDS adding coordinate var
iable TIME for dimension TIME
2022-07-26T20:26:05.692 +0000 [    128972][       7] INFO  - threddsServlet - Request Completed - 200 - -1 - 188
2022-07-26T20:26:30.063 +0000 [    153343][       8] INFO  - threddsServlet - Remote host: 161.55.46.63 - Request: "GET
/thredds/dodsC/pile/coads_avg.jnl.ascii?sst_avg%5B40:1:50%5D%5B30:1:40%5D HTTP/1.1"
2022-07-26T20:26:30.066 +0000 [    153346][       8] DEBUG - thredds.server.opendap.OpendapServlet - doGet(): User-Agent
 = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
2022-07-26T20:26:30.066 +0000 [    153346][       8] DEBUG - thredds.server.opendap.OpendapServlet - OpendapServlet: nom
inal url: https://dunkel.pmel.noaa.gov:8940/thredds/dodsC/pile/coads_avg.jnl.ascii?sst_avg[40:1:50][30:1:40]
2022-07-26T20:26:30.066 +0000 [    153346][       8] DEBUG - thredds.core.DatasetManager - DatasetHandler wants pile/coa
ds_avg.jnl
2022-07-26T20:26:30.068 +0000 [    153348][       8] ERROR - thredds.server.opendap.OpendapServlet - request= ReqState:
  serverClassName:    'null'
  dataSet:            'pile/coads_avg.jnl'
  requestSuffix:      'ascii'
  CE:                 'sst_avg[40:1:50][30:1:40]'
  compressOK:          true
  InitParameters:

java.lang.IllegalArgumentException: null
        at ucar.nc2.util.cache.FileCache.acquire(FileCache.java:245) ~[cdm-core-5.5.3.jar:5.5.3]
        at ucar.nc2.util.cache.FileCache.acquire(FileCache.java:216) ~[cdm-core-5.5.3.jar:5.5.3]
        at ucar.unidata.io.RandomAccessFile.acquire(RandomAccessFile.jav
```

 with the steps needed to reproduce it:

I'm hoping you can see something from just the information in this issue, but I will create a [pre-release here](https://github.com/NOAA-PMEL/ftds/releases/tag/v9.0-alpha) if you're willing to go to all the bother of trying it out locally.  Otherwise, I can try to give you more information from my set up.

**Comment by haileyajohnson** [comment]
Is any more of the stack trace on the `IllegalArgumentException` available? I'm guessing something is going awry with the `DatasetUrl` somewhere in the TDS...

**Comment by noaaroland** [comment]
Here's the entire threddsServlet.log up to the point where the error occurs
[threddsServlet.log.txt](https://github.com/Unidata/tds/files/9223975/threddsServlet.log.txt)
.

**Comment by haileyajohnson** [comment]
@noaaroland from the limited testing that I've done, I don't think the issue is related to the IOSP at all - could you share the catalog that referencing the dataset?

**Comment by haileyajohnson** [comment]
Actually, could you also test hitting this endpoint directly: `/thredds/dodsC/pile/coads_avg.jnl.ascii?sst_avg%5B40:1:50%5D%5B30:1:40%5D` without first loading the html view?

**Comment by noaaroland** [comment]
Hitting the URL directly worked!

```
Dataset {
    Grid {
     ARRAY:
        Float32 sst_avg[COADSY = 11][COADSX = 11];
     MAPS:
        Float64 COADSY[COADSY = 11];
        Float64 COADSX[COADSX = 11];
    } sst_avg;
} pile/coads_avg.jnl;
---------------------------------------------
sst_avg.sst_avg[11][11]
[0], 28.445631, 28.401016, 28.296896, 28.601746, 28.339485, 28.310516, 28.330748, 28.135244, 28.159214, 28.386347, 28.411179
[1], 28.241295, 28.166744, 28.25907, 28.403677, 28.304232, 28.401659, 28.46219, 28.279861, 28.24345, 28.495356, 28.305344
[2], 28.30932, 28.433199, 28.364067, 28.400194, 28.454483, 28.409872, 28.610353, 28.654978, 28.575872, 28.653528, 28.553154
[3], 28.343596, 28.461838, 28.54841, 28.585947, 28.54616, 28.832758, 28.6088, 28.578009, 28.597216, 28.513609, 28.630522
[4], 28.605564, 28.507832, 28.5592, 28.669252, 28.715714, 28.70427, 28.602926, 28.737793, 28.940075, 28.69626, 28.060535
[5], 28.560211, 28.556404, 28.580076, 28.526346, 28.627472, 28.733234, 28.478304, 28.544323, 28.880949, 28.556961, 28.136076
[6], 28.343693, 28.396366, 28.501503, 28.463877, 28.42691, 28.617224, 28.607979, 28.9724, 28.961168, 28.577467, 28.489689
[7], 27.974127, 28.086004, 28.179396, 28.249937, 28.272997, 28.30672, 28.366125, 28.410269, 28.456598, 28.49212, 28.662348
[8], 27.806583, 27.870283, 28.20378, 28.256552, 28.292063, 28.343725, 28.405588, 28.429777, 28.422249, 28.400787, 27.618006
[9], 27.635693, 27.627493, 27.77639, 27.862625, 27.960133, 27.825119, 28.096594, 28.298105, 28.30476, 28.134634, 27.835796
[10], 27.318228, 27.385546, 27.447113, 27.610056, 27.53749, 27.693047, 28.05349, 27.97219, 28.197794, 27.506245, 28.015593

sst_avg.COADSY[11]
-9.0, -7.0, -5.0, -3.0, -1.0, 1.0, 3.0, 5.0, 7.0, 9.0, 11.0

sst_avg.COADSX[11]
81.0, 83.0, 85.0, 87.0, 89.0, 91.0, 93.0, 95.0, 97.0, 99.0, 101.0
```

**Comment by noaaroland** [comment]
The catalog for this data set looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<catalog name="THREDDS Server Default Catalog : You must change this to fit your server!"
         xmlns="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0"
         xmlns:xlink="http://www.w3.org/1999/xlink"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0
           https://schemas.unidata.ucar.edu/thredds/InvCatalog.1.0.6.xsd">

  <service name="all" base="" serviceType="compound">
    <service name="odap" serviceType="OpenDAP" base="/thredds/dodsC/"/>
    <service name="dap4" serviceType="DAP4" base="/thredds/dap4/"/>
    <service name="http" serviceType="HTTPServer" base="/thredds/fileServer/"/>
    <service name="wcs" serviceType="WCS" base="/thredds/wcs/"/>
    <service name="wms" serviceType="WMS" base="/thredds/wms/"/>
    <service name="ncssGrid" serviceType="NetcdfSubset" base="/thredds/ncss/grid/"/>
    <service name="ncssPoint" serviceType="NetcdfSubset" base="/thredds/ncss/point/"/>
    <service name="cdmremote" serviceType="CdmRemote" base="/thredds/cdmremote/"/>
    <service name="iso" serviceType="ISO" base="/thredds/iso/"/>
    <service name="ncml" serviceType="NCML" base="/thredds/ncml/"/>
    <service name="uddc" serviceType="UDDC" base="/thredds/uddc/"/>
  </service>
  <datasetScan name="A Pile of Data" path="pile" location="/home/users/rhs/data" >
    <serviceName>all</serviceName>
  </datasetScan>
</catalog>
```

**Comment by haileyajohnson** [comment]
I am, unfortunately, having a hard time getting your IOSP set up to debug. It seems like the file is being changed or moved during the first request to load the html.
Could you test whether you can make two subset requests in a row (again, without requesting the html page first)? I'm trying to narrow down where the error is being introduced.

I'll keep trying to get a debug set up going.

**Comment by noaaroland** [comment]
I understand. It's a bit of a rube goldberg machine. I've only set it up the one time and then typed up the instructions.  I'm happy to help you debug your setup if you want to meet over video chat or some such.

I cleared my IOSP cache and did the first request. It worked. I changed the index of the sub-set and in the URL and that request failed. You can see the two requests in the attached log excerpt.

[thredds_log.txt](https://github.com/Unidata/tds/files/9354660/thredds_log.txt)
.

**Comment by bruinbryan** [comment]
@haileyajohnson   Just checking if you made any progress debugging the IOSP ?  @noaaroland  has offered to help if you need assistance.   The issue has triggered NASA security, which is why I need to monitor this issue.

**Comment by haileyajohnson** [comment]
I have been out of the office most of this week and have no had time to keep investigating.
It doesn't seem to be an issue with the plugin mechanism.

A suggestion from @lesserwhirls is that there might be a problem accessing the cache with the old NetcdfFile api. Could you try upgrading invocations of `NetcdfFile.open` and `NetcdfDataset.open` (now deprecated) to the static methods `NetcdfFiles.open` and `NetcdfDatasets.open`? 
E.g. [here ](https://github.com/NOAA-PMEL/ftds/blob/6105239f9766dfbd045e9eb20094530f180b85ae/src/main/java/sdig/ftds/iosp/FerretIOServiceProvider.java#L249)and [here](https://github.com/NOAA-PMEL/ftds/blob/6105239f9766dfbd045e9eb20094530f180b85ae/src/main/java/sdig/ftds/iosp/FerretIOServiceProvider.java#L735)

**Comment by noaaroland** [comment]
I changed the two open methods. I didn't find any others. The only other deprecated code I'm using is in the DatasetSource implementation. (As an aside, I did not find any definition of the DatasetSource interface in any of the public jars.) I just have the interface source ripped from THREDDS source in my project.

I do not know how to construct a NetcdfFile object and include the random access file using the new builder as is required to satisfy the getNetcdfFile call in the interface definition AFAIK.

F-TDS does it's own caching. If the THREDDS caching is the problem, then a way to turn it off for any data set that uses the IOSP might work if such a thing is possible.

After I made the changes to the two open calls, the IOSP worked in TDS on correctly on every other request. I can't say for sure anything changed because I never tested more than two requests in a row previously.

**Comment by haileyajohnson** [comment]
Hi @noaaroland , just now getting back into this issue. As far as I can tell, DatasetSource is not a pluggable interface in the TDS anymore, which, if true, is fully our bad for still having it [documented](https://docs.unidata.ucar.edu/tds/current/userguide/dataset_source_plugin.html). Are you directly calling your DatasetSource or relying on the TDS to call it? Because I don't think the TDS will be able to find it. 

This still doesn't explain why the call would fail/succeed on every other request though, so I'm still puzzling through that.

**Comment by haileyajohnson** [comment]
Ok it took some time but I finally got your IOSP up and running in a dev instance - basically every other request is failing because it recognizes that it's already opened the file, and is telling your iosp to `reacquire` the file based on the `location` property, which you haven't set. 

All you need to do to get it working is add this line to your `iosp.build` method:
`this.location = raf.getlocation();`

**Comment by noaaroland** [comment]
The ISOP appears to work when plugged into THREDDS with the suggested change when accessing a script file which is already on disk. The idea behind the DatasetSource plug is to allow a file to be created dynamically with the lines of the Ferret script embedded in the URL. 

I haven't been able to get that to work and it's not clear from the information above if the DatasetSource has or will be implemented (the interface is not in the jar). 

And, I couldn't really do the implementation in the same way as before since the method I used before has been deprecated.  

Can I expect to be able to use the DatasetSource interface to make virtual variables as was done in version 4?

An example, which you can try in your setup is a URL that looks like this where you would replace the server and path with the correct information for your setup and leave the _expr_ as is:

https://dunkel.pmel.noaa.gov:8940/thredds/dodsC/las/coads_climatology_cdf/data_coads_climatology.jnl_expr_%7B%7D%7Bletdeq1+airt_1_transformed%3Dairt%5Bd%3D1%2Cx%3D160.3125%3A215.15625%40Average%2Cy%3D11.25%3A49.21875%40Average%5D_cr_ATTRCMD+airt+airt_1_transformed%7D


Feel free to close this ticket and open a new ticket on the subject of DatasetSource

**Comment by haileyajohnson** [comment]
I think this does actually work via the method describe [here](https://docs.unidata.ucar.edu/tds/current/userguide/dataset_source_plugin.html). The interface and the plugin hooks are still there, and I'm able to hit that code. Two questions that might help:

1) do you see anything in the logs like `Attempt to load DatsetSource class FerretDataSource not found"?
2) do you have this line in threddsConfig: `<datasetSource>sdig.ftds.iosp.FerretDataSource</datasetSource>

**Comment by noaaroland** [comment]
Yes, I have the datasetSource element in my threddsConfig.xml with my class.

I looked at this again after studying the example. I exploded the TDS war file and collected the class files into a jar so I would have access to thredds.servlet.DatasetSource since doesn't seem to be in any of the other jar files.

I reworked my DatasetSource implementation to use this:

```
 NetcdfFile ncfile = NetcdfDatasets.openFile(ferret_script_file_path, null);  // with an "s" at the end since the one without is deprecated...
```
And it seems to work. I have more testing to do, but the fundamentals seems to be working.

**Comment by haileyajohnson** [comment]
The `DatasetSource` class file can be found in this [jar](https://artifacts.unidata.ucar.edu/repository/unidata-all/edu/ucar/tds/5.4/tds-5.4-classes.jar). But that's great! I'm going to close this issue, but feel free to open a new one if your testing exposes more issues!
