### ISSUE TITLE
'Download All top-level collection indicies' results in empty zip archive

### ISSUE THREAD

**Issue by rjdave** [Unidata/tds#263]
THREDDS-5.5-SNAPSHOT from 07-26-2022
CentOS 7, AdoptOpenJDK 11.0.15+10, Tomcat 8.5.75

When using the `admin/debug` interface and navigating to the "Show Collections" link, there is a link at the bottom titled "Download All top-level collection indicies". Clicking that link downloads a file named`downloadAll` that is only 22 bytes and appears to be an empty Zip archive according the `file` command.

Likewise, the "Collection Status CSV" link directly above takes you to a mostly blank page that has only the following line displayed:

`collection, ed, type, group, nrecords, ndups, %, nmiss, %`

**Comment by tdrwenski** [comment]
The "download all indices" does contain index files for me when some of the collections are grib collections. I think your zip is empty because the FMRC datasets do not have index files (see also my comment here: https://github.com/Unidata/tds/issues/238)

**Comment by rjdave** [comment]
I do not have any grib collections so that explains it.
