### ISSUE TITLE
links on `collection/showStatus` page return tomcat 404 not found page

### ISSUE THREAD

**Issue by rjdave** [Unidata/tds#264]
THREDDS-5.5-SNAPSHOT from 07-26-2022
CentOS 7, AdoptOpenJDK 11.0.15+10, Tomcat 8.5.75

When using the `admin/debug` interface and navigating to "Show Collections" -> "Show All Collection Status", all the links to FMRC datasets on that page result in an Apache Tomcat 404 not found page:

```
HTTP Status 404 – Not Found

Type: Status Report

Description: The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
Apache Tomcat/8.5.75
```

All links are of the form: `https://<hostname>:<port>/thredds/admin/collection?collection=<collection_name>`

**Comment by tdrwenski** [comment]
Yes, it seems like that collection status page is missing in TDS 5. I will see if I can add that back.

**Comment by tdrwenski** [comment]
I fixed those broken links to lead to what I think is the same collection status page you could access with TDS 4.

Here is the newest snapshot: https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/edu/ucar/tds/5.5-SNAPSHOT/tds-5.5-20220809.202414-26.war

**Comment by rjdave** [comment]
The links are working but they link to the exact same page that is displayed when clicking the collection name on the page that contains the "Show All Collection Status" link. Perhaps it was abandoned for that reason?

**Comment by tdrwenski** [comment]
Yeah, it is not that useful indeed. I'm not sure how many people are using the admin page, so I'm not sure if it is worth the effort to improve it much at this time.
