### ISSUE TITLE
Delete FMRC Cache for a Single Collection

### ISSUE THREAD

**Issue by rjdave** [Unidata/tds#265]
THREDDS-5.5-SNAPSHOT from 07-26-2022
CentOS 7, AdoptOpenJDK 11.0.15+10, Tomcat 8.5.75

In the `admin/debug` interface in THREDDS 4.6 you can delete the FMRC cache for a single collection by navigating to "Show FMRC Cache" -> "<dataset_name>" and clicking the "Delete" link at the top of the resulting page. Is the same functionality available somewhere in THREDDS 5?

**Comment by tdrwenski** [comment]
I don't think this is possible in TDS 5, is there a reason why you need this functionality?

**Comment by rjdave** [comment]
That depends on what information is actually stored in the FMRC cache for THREDDS 5. In 4.6, whenever we had to modify a dataset, we would need to clear the cache for new variables to be read or deleted ones to be removed. I believe on a couple occasions the cache was corrupted and we needed to delete and rebuild it for the dataset to be usable. I'll admit this was rare but it takes hours and hours to rebuild the cache for all the datasets if we encounter similar situations and would have to delete the entire fmrc cache.

An unsavory alternative would be renaming the dataset every time we make changes or have a corruption. This would be inconvenient and eventually make the cache full of defunct datasets.

Is there a way to force THREDDS 5 to re-read every file and rebuild the cache instead of just looking for new files?

**Comment by tdrwenski** [comment]
I believe that if you update anything in your collection files, that sending a "trigger=test" will be enough to update the collection. The cache (now managed by ChronicleMap) is there to keep persistence between reboots and it updates itself if it is out of date. So I don't think you should have to clear the cache manually for a dataset. Of course, if you do have problems related to caching, let us know and we will take a closer look!
