### ISSUE TITLE
Scan S3 bucket and list files with THREDDS 5

### ISSUE THREAD

**Issue by vietnguyengit** [Unidata/tds#271]
Hi all,

This issue is kind of similar to this one: https://github.com/Unidata/tds/issues/194

However, reading through previous conversations, especially these comments: https://github.com/Unidata/tds/issues/194#issuecomment-1070238622 and this https://github.com/Unidata/tds/issues/194#issuecomment-1094112228 

It sounds to me that you want to close the issue with a "solution": listing NetCDF files from an S3 bucket by hard-coded to the individual file level.

e.g
```xml
<dataset name="test prism" ID="prism" urlPath="nhgf/thredds/prism_v2/prism_2020.nc"  dataType="Grid" serviceName="all"/>
```

and the  `<scan location="cdms3:bucketname/path/to/objects_shared_location>` tag works with aggregated dataset?

What if I have an S3 bucket with this sample structure:

```
my-s3-bucket
|__Agro
|    |__Atlantic
|    |    file0.nc
|    |    ...
|    |    file1000.nc
|    |    
|    |__Antarctica
|    |    afile0.nc
|    |    ...
|    |    afile5000.nc
|    |    
|    |__Pacific
|         somefile0.nc
|         ...
|         somefile3000.nc
|         
|__SST
|    |__Collections
|         xyz0.nc
|         ...
|         many-files100.nc
|         
|__AUV
|    |__Australia
|         random-name0.nc
|         ...
|         100th-file.nc
|    
|__Mooring
     |__Australia
          random-name0.nc
          ...
          300th-file.nc
```

It works on my side with what you have in https://github.com/Unidata/tds/issues/194 by hard-coded individual files, but to achieve the ultimate goal ... having the S3 structure above listed on THREDDS 5 automatically, it's unwise to hard code thousands of files...

Something like this: https://ihthredds.ihcantabria.com/thredds/catalog.html

It's not a big deal to the hard-code catalog XML file for root folder level, even with folders such as `Argo`, `AUV`, `SST`, `Moorings`...But it's a problem to hard-code sub-folders of those folders, it could be hundreds nested sub-folders structure...
 
So, I wonder if THREDDS 5 with native features like `<scan>` tag `cdms3` or something else capable of scanning/listing/creating `XML` files catalog structure matching with S3 bucket structure with complex filename patterns, many folders/sub-folders, and thousands of files? If so, what do I need to look at?

I think this is a quite helpful thing that needs to be natively supported because storing NetCDF files on S3 buckets is a common practice of many organizations nowadays.

Thank you.

**Comment by tdrwenski** [comment]
Greetings!

If I understand correctly, you want to serve all files in a "directory"  as datasets without having to manually list each in your catalog. We have such a catalog feature for ordinary files, called the `datasetScan` (https://docs.unidata.ucar.edu/tds/current/userguide/tds_dataset_scan_ref.html).

However, unfortunately `datasetScan`s do not yet work for S3, but it is definitely still on our "to do" list.

**Comment by vietnguyengit** [comment]
Hi @tdrwenski , yes you're correct, I also have datasetScan to work with disk files. Thanks for confirming that it's yet supported for S3 files.
