### ISSUE TITLE
Opendap problem with NEXRAD and unsigned

### ISSUE THREAD

**Issue by dopplershift** [Unidata/tds#277]
If you access NEXRAD level2 data on our thredds server using opendap (e.g. https://thredds.ucar.edu/thredds/catalog/nexrad/level2/KSRX/20220902/catalog.html?dataset=NWS/NEXRAD2/KSRX/20220902/Level2_KSRX_20220902_1917.ar2v), the data are not being served correctly.

For instance, the maximum value for the `Reflectivity_HI` variable comes back as 127, and then wraps around to negative values. Meanwhile, for CDMRemote, that max value is 184. This is obviously problematic when you then scale to floating point.

I haven't checked all values, but it definitely applies to Correlation Coefficient as well.

(Esupport JKR-918279)

cc @DennisHeimbigner

**Comment by DennisHeimbigner** [comment]
I see that the type of Reflectivity_HI is "Byte", which is unsigned in DAP2.
There is no attribute indicated that it should be treated as signed.
So not sure why it is coming out as signed.

**Comment by DennisHeimbigner** [comment]
Is there anyway we can look at the underlying file in toolsui to see what kind of
CDM is being produced?

**Comment by dopplershift** [comment]
This was working in TDS 4, but I seem to recall that TDS 5 "modernized" the unsigned handling. Maybe the update for the DAP2 code was faulty (or left undone).

**Comment by dopplershift** [comment]
Well you can download the file [here](https://thredds.ucar.edu/thredds/fileServer/nexrad/level2/KSRX/20220902/Level2_KSRX_20220902_1917.ar2v). So assuming you can run ToolsUI that should be trivial?

**Comment by DennisHeimbigner** [comment]
>Maybe the update for the DAP2 code was faulty (or left undone).

I can easily believe that.

**Comment by lesserwhirls** [comment]
> This was working in TDS 4, but I seem to recall that TDS 5 "modernized" the unsigned handling. Maybe the update for the DAP2 code was faulty (or left undone).

I'm not sure that it was touched. The "modernizing" I was going to was to redo the code to always widen integral types to match an actual dap 2 type, but I decided against it to keep the behavior consistent. There were some changes to how the underlying Java objects represent unsigned types though, and that could be cropping up here.

As a troubleshooting data point, however, the ASCII response from the DAP2 server shows the correct values.

**Comment by DennisHeimbigner** [comment]
Have you checked to see if the bit patterns are the same.
For example (unsigned char)184 has the same bit pattern as
(signed char)-72.

**Comment by DennisHeimbigner** [comment]
Also, what tool are you using to access the opendap url?

**Comment by dopplershift** [comment]
@DennisHeimbigner I haven't done any more than I posted above, since I don't have the cycles, and I'm not going to be able to fix DAP myself anyway. I used ncdump to look at the output from THREDDS. You can see the problem right away for correlation coefficient:

`ncdump -v "CorrelationCoefficient_HI" https://thredds.ucar.edu/thredds/dodsC/nexrad/level2/KSRX/20220902/Level2_KSRX_20220902_1917.ar2v`

gives:

```
<snip>
 CorrelationCoefficient_HI =
  -85, -75, -68, -79, 87, 92, 90, 91, 104, -44, -59, 75, -102, -66, 0, -33, 
    -105, 96, 101, -70, -113, -48, 46, 52, 61, 74, 96, -112, 103, 79, 88, 
    -96, -65, -77, -107, -112, -115, -109, -56, -92, -126, 127, 127, -128, 
    76, 106, -30, -79, 117, 2, 46, -103, -29, -37, -106, -113, -104, -90, 28, 
    120, -82, -49, -45, -25, -121, 115, 74, 74, 92, 118, -100, -79, 2, -53, 
    126, -70, -74, -78, -83, -69, -67, 99, 125, -106, -91, -82, -76, -72, 
    -95, 25, 72, 32, 58, 85, 113, -115, 2, -97, -52, 96, 70, 117, -94, -57, 
    94, 43, 118, -110, 100, -113, -124, 68, 36, -97, -90, 120, 102, 95, 93, 
    -61, -96, -47, -107, 62, -29, -37, -53, -66, -70, -44, -44, -29, -38, 
    -101, -70, 80, -98, 67, -105, -50, -79, -69, -55, -68, -36, 21, 42, 69, 
    109, -79, -125, -98, -23, -1, 0, -1, 54, -1, -40, -1, 51, -1, -17, -95, 
</snip>
```

**Comment by DennisHeimbigner** [comment]
[The problem is this. netcdf-c maps DAP2 to netcdf-3 format.
In DAP2, the type of CorrelationCoefficient_HI is byte, which in DAP2
is equivalent to the C type unsigned char.
The netcdf-3 format byte type, however, is equivalent to the C type signed char.
So, when reading the DAP2, the netcdf library attempts to keep the same
bit pattern, but the type is signed char. You can see this with the first value.
In DAP2, this is 171, but in netcdf-3, this is mapped to -85. Note that
at the binary level the 8 bits of 171 are the same as the 8 bits of -85.

**Comment by DennisHeimbigner** [comment]
Also, the Java ncdump gets it right because it is not restricted to netcdf-3

**Comment by dopplershift** [comment]
That they are the same bit pattern makes complete sense, and I agree with your analysis. We need to do something to fix this, though, because it's returning incorrect data--and this used to work just fine in TDS 4.x.

**Comment by DennisHeimbigner** [comment]
My speculation about why it used to work is that the DAP2 code
was up-casting the DAP2 unsigned byte to type short.

**Comment by dopplershift** [comment]
My recollection from the previous times I've dealt with this is that this was all handled by the `_Unsigned` attribute. Here's the code in [netcdf-c handling this](https://github.com/Unidata/netcdf-c/blob/bee23ee02672805bc988eca86ea6e017a93bc990/libdap2/ncd2dispatch.c#L786-L804):
```c
	if(var->attributes != NULL) {
	    NCattribute* unsignedatt = NULL;
	    int unsignedval = 0;
	    /* See if variable has _Unsigned attribute */ 
	    for(j=0;j<nclistlength(var->attributes);j++) {
		NCattribute* att = (NCattribute*)nclistget(var->attributes,j);
		if(strcmp(att->name,"_Unsigned") == 0) {
		    char* value = nclistget(att->values,0);
		    unsignedatt = att;
		    if(value != NULL) {
			if(strcasecmp(value,"false")==0
			   || strcmp(value,"0")==0)
			    unsignedval = 0;
			else
			    unsignedval = 1;
		    }
		    break;
		}
	    }
```

and thanks to @lesserwhirls, it looks like the TDS *should* be sending the attribute, but isn't:
https://github.com/Unidata/tds/blob/f0a6297f6fd8b9e4cb3ee2b29312ce64eda94458/tds/src/main/java/thredds/server/opendap/NcDAS.java#L135-L141

Looks like the [DDS response](https://thredds.ucar.edu/thredds/dodsC/nexrad/level2/KLTX/20220906/Level2_KLTX_20220906_2209.ar2v.dds) has the variables as `Byte`, but the [DAS response](https://thredds.ucar.edu/thredds/dodsC/nexrad/level2/KLTX/20220906/Level2_KLTX_20220906_2209.ar2v.das) does not have the `_Unsigned` attribute on any of those variables.

**Comment by DennisHeimbigner** [comment]
I expect that the netcdf-c DAP2 code defaults the DAP2 byte type
to be Unsigned, since it (DAP2 byte) already is. The needed change is for 
netcdf-c DAP2 code to up-cast to short type. I do not
recall that we ever have supported that.

**Comment by dopplershift** [comment]
@DennisHeimbigner Why does netcdf-c need to change if this worked for TDS 4.x? I don't understand why any upcasting would be necessary.

I think the problem here is that for some reason, TDS 5 stopped sending the `_Unsigned` attribute. Now there's another question of: Shouldn't the default mapping in netcdf-c just be DAP2 `Byte` -> `NC_UBYTE`?

**Comment by DennisHeimbigner** [comment]
But netcdf-3 does not have the NC_UBYTE type, nor any other unsigned types.

**Comment by dopplershift** [comment]
In some ways that makes sense, and in others I'm not sure why netcdf-3's limitations matter when:

1. netcdf4 doesn't have the limitation
2. I didn't ask for it to limit to netcdf-3
3. It's a lossy mapping of DAP2 when it doesn't have to be

**Comment by DennisHeimbigner** [comment]
What tool are you using to read this? netcdf-java or netcdf-c?
Also, what version?

**Comment by dopplershift** [comment]
`ncdump` from conda-forge's libnetcdf 4.8.1. This is also seen by conda-forge netcdf4-python, which uses the same version of libnetcdf (netcdf-c).

**Comment by dopplershift** [comment]
With the new snapshot that has #279 included, netcdf4-python decodes the data properly because it has direct support for the `_Unsigned` attribute. netcdf-c still shows the values as negative. All the user-facing reported issues are solved.

To me there's an open question of whether netcdf-c should be doing something here, but I think the regression in TDS v5 at least is fixed.

(cc @WardF)

**Comment by WardF** [comment]
Thanks for tagging me in @dopplershift, I hadn't seen this.  I've taken a quick pass and am dumping my thoughts out below. 

So the question of what to do based on the `_Unsigned` attribute is an interesting one.  With `DAP2` being limited to `netCDF3`, it would be weird to see a value outside the valid range as defined by the `netCDF3` data model, e.g. `byte` values > 127.  The `_Unsigned` attribute tells whoever is interpreting the data 'the bit pattern as represented in netCDF3 is this (potentially) negative value, but if it's negative it will require manual interpretation'.  Normally, this sort of interpretation would be handled by logic in whatever software is invoking `libnetcdf-c` calls;  casting the data type, etc.

It feels like there might be room in the command line utilities to convert data types, if the appropriate argument is given.  I'm thinking specifically about a flag in `nccopy` and `ncdump` that says 'hey, if `_Unsigned = true` is encountered, copy/print the unsigned representation of this value', as necessary.  That way, `ncdump` could represent this data, and if using `nccopy` to copy from a `classic` to a `netcdf4/netcdf4 classic` file, the data type could be converted.  

I'll need to think about that more, but at the moment I would agree that 1. We're seeing values represented in a way that is unexpected and inconsistent with the expectation developed through common practice, and 2. The 'expected' values cannot be represented by the netCDF3 data model, hence the adoption of the `_Unsigned` convention.  

We'll sort this out, but at least we can feel better that it's just the *representation* of the value that is unexpected; the data itself is correct.
