### ISSUE TITLE
TDS 5.4 (ncss)  wrongly detects bounding box for the data

### ISSUE THREAD

**Issue by rkouznetsov** [Unidata/tds#283]
Same 5.4 setup from https://github.com/Unidata/tds/issues/282.
http://thredds.silam.fmi.fi/thredds/ncss/grid/silam_glob06_v5_8/files/SILAM-AQ-glob06_v5_8_2022091200_001.nc4/dataset.html

Thredds suggests that east and west boundaries are the same: -179.700, whereas the file ranges from -179.7 to 179.7 degrees.

By selecting a variable (e.g. Total CO column) and submitting a request URL string at the bottom of the page one gets
```
Request Too Large: lonaxis: longitude want [180.300000,180.300000] does not intersect lon axis [-179.399994,180.000031];
```
When selecting a reasonable bounding box manually, request succeeds.
It would be great if threads could interpret coordinate variables properly. 
Thank you!

**Comment by rkouznetsov** [comment]
Also note 
`geospatial_lon_min` and `geospatial_lon_max` attributes in `thredds.new.nc` form https://github.com/Unidata/tds/issues/282
I guess, it is the same issue...

**Comment by haileyajohnson** [comment]
I believe this is already fixed by [this PR](https://github.com/Unidata/netcdf-java/pull/1051). Also, #282 is likely also working in the latest snapshot, if you'd like to try that out, you can get it [here](https://downloads.unidata.ucar.edu/tds/)

**Comment by rkouznetsov** [comment]
Thank you! Updating  to thredds-5.5-SNAPSHOT.war fixed this issue.
