### ISSUE TITLE
DAP4  with thredds?

### ISSUE THREAD

**Issue by rkouznetsov** [Unidata/tds#285]
We have got quite spectacular  intermittent data corruptions when downloading large datasets over DAP from TDS4.6: the values of some two variables were mixed up. The occasions were rare enough to make the issue reproducible, but often enough to cause a headache. A work-around was to download the same file many times (usually two) until two files with identical MD5sum obtained, which is an abuse of the server capacity and the network bandwidth.

 I have spotted that DAP does not have any redundancy, checksum, or any other means to validate the transfer, and looked towards DAP4 which has some redundancy. DAP4 did not work for me a year ago in TDS4.6, and the support suggested me to update to TDS5. It does not seem to work in TDS5.5-SNAPSHOT ether, but, hopefully, it can be fixed..

When I click on DAP4 from e.g. https://thredds.silam.fmi.fi/thredds/catalog/silam_glob06_v5_8/files/catalog.html?dataset=silam_glob06_v5_8/files/SILAM-AQ-glob06_v5_8_2022091400_001.nc4
 I get "HTTP Status 500 – Internal Server Error". 

The error appears in catalina.out, but not in any of thredds logs. see attached
[out.log.gz](https://github.com/Unidata/tds/files/9583217/out.log.gz)

Thank you!

**Comment by tdrwenski** [comment]
Dap4 doesn't currently work with TDS 5, but we are working on getting it fixed. I don't think it shouldn't be allowed as a service right now as it doesn't work-- I think that was an oversight, I will check on that.

**Comment by rkouznetsov** [comment]
Thank you for the info! I have disabled DAP4 from catalog.xml. 
Looking forward to see DAP4 working. Hopefully it will be a good replacement for the DAP2 protocol.
