### ISSUE TITLE
FYI: Simultaneous testing netcdf-java + tds under github actions

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/tds#338]
[Note: This is an FYI rather than an Issue per-se]

Sometimes it is necessary to simultaneously modify netcdf-javaand tds in order to test some new feature that involves both repositories.

One way to do this is to build netcdf-java and insert it into an artifact server such as Nexus. Then run a github action in the tds repository that references that artifact. This can be very cumbersome when the testing cycle is rapid. It is impossible if you are a non-Unidata person who cannot access the artifact server at all.

I have found a good alternative here: "https://github.com/melix/includegit-gradle-plugin". It is a gradle plugin that downloads some branch of netcdf-java (or a fork of it) and uses that instead of the artifact server. More detailed documentation can be found [**here**](https://melix.github.io/includegit-gradle-plugin/latest/index.html).

Basically it requires two changes in order to use it.

First, you need to modify your tds' "settings.gradle" file to place code like the following at the top of the file.
````
plugins {
  id 'me.champeau.includegit' version '0.1.5'
}
gitRepositories {
  include('netcdf-java') {
    uri = 'https://github.com/DennisHeimbigner/netcdf-java.git'
    branch = 'branch-name'
  }
}
````
The "branch-name" is the netcdf-java branch you want to use in your github actions testing.
The uri points to the netcdf-java github repository or to some fork of it. In the case above, it is pointing to a fork.
If your branch happened to be in the base Unidata netcdf-java repository, then you might use this:
````
    uri = 'https://github.com/Unidata/netcdf-java.git'
````
In either case, the branch is with respect to that repository uri.

The second change is to ensure that the most recent version of the branch is used (rather than some older cached version). You need to modify the files 'tds/.github/workflows/deps.yml' and 'tds/.github/workflows/tds.yml' to add a parameter to the gradlew commands.

For 'tds/.github/workflows/deps.yml', you need to change the line:
````
        run: ./gradlew clean classes testClasses assemble --refresh-dependencies
to
        run: ./gradlew clean classes testClasses assemble --refresh-dependencies -Drefresh.git.repositories=1L
````

Similarly, for 'tds/.github/workflows/tds.yml', you need to change the line:
````
          test-command: '--debug -Dtds.content.root.path=$CONTENT_DIR -Dtds.test.gretty.container=${{ matrix.servletcontainer }} --info --stacktrace testAll'
to
          test-command: '--debug -Dtds.content.root.path=$CONTENT_DIR -Dtds.test.gretty.container=${{ matrix.servletcontainer }} --info --stacktrace testAll -Drefresh.git.repositories=1L'
````

**WARNING: remember to remove these changes before final commit so they do not end up in the main branch of tds.**

**Comment by tdrwenski** [comment]
I will close this, since this is more developer documentation than an issue to be fixed.
