### ISSUE TITLE
Pointing tds.content.root.path into webapp directory...

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/tds#340]
I have a scenario where everytime I reload thredds (aka tds) to Tomcat, it wipes out the existing tds.content.root.path directory and rebuilds it using altContent.
Suppose the following:
1. CATALINA_HOME=/opt/xxx
2. Tomcat webapp directory is: /opt/xxx/webapps
3. thredds.war (the servlet) is unpacked into /opt/xxx/webapps/thredds

If I set:
> tds.content.root.path=/opt/xxx/webapps/thredds/content

Will it be the case that everytime I re-upload and deploy thredds.war (via the Tomcat admin page) it will wipe out the existing "/opt/xxx/webapps/thredds/content" and rebuild it from altContent? Has anyone tried this?

**Comment by haileyajohnson** [comment]
For a persistent content between deployments, you need to place the content dir outside the webapps folder, otherwise yes, it is expected that it will be rebuilt.
