### ISSUE TITLE
Unstructured grids - UGRID from a TDS 

### ISSUE THREAD

**Issue by PBrockmann** [Unidata/tds#343]
I have read this proposal and I am wondering if the project https://github.com/ioos/thredds-ugrid has been finally merged into the current Thredds code.

This proposal was a really good initiative.
https://github.com/ioos/thredds-ugrid/blob/master/documents/proposal/2018-0196%20Proposal_Narrative_redacted.pdf
How did this project ended ?

I am looking for an infrastructure able to deliver a WMS for UGRID ressources.
Let me know.

**Comment by haileyajohnson** [comment]
I believe this work is more or less complete but still needs testing... @lesserwhirls can probably provide more information

**Comment by PBrockmann** [comment]
I would be really interested to test it.
There are a couple of files from https://geoport.whoi.edu/ but can provide output from our icosahedral hydrostatic model.

**Comment by PBrockmann** [comment]
Any news ? Having a calendar in mind would be kind.

**Comment by lesserwhirls** [comment]
The general work is complete, and FMRCs can be created using UGRID datasets. The work is not available in the current release (v5.4), but will be in the next release (and should be available in the current v5.5 SNAPSHOTS, available at https://downloads.unidata.ucar.edu/tds/). The WCS service will not work with UGRID datasets, and NCSS currently does not work with UGRID datasets (but will be with a bit more work). An example of a UGRID FMRC can be found here:

https://github.com/Unidata/tds/blob/dda75f8639631db32221405fe017047c1524c4da/tds/src/test/content/thredds/catalogFmrc.xml#L78-L87

The definition of the "ugrid" service is:

https://github.com/Unidata/tds/blob/dda75f8639631db32221405fe017047c1524c4da/tds/src/test/content/thredds/catalog.xml#L24-L32

**Comment by PBrockmann** [comment]
Very good.
Is the WMS will be available for UGRID datasets ?

**Comment by lesserwhirls** [comment]
> Very good.
> 
> Is the WMS will be available for UGRID datasets ?

Yes.

**Comment by lesserwhirls** [comment]
I do not - I am no longer an employee at Unidata, and I do not run a TDS from home. Docker might be the easiest way to test.

**Comment by haileyajohnson** [comment]
> Impatient to test it. Do you have a TDS available for testing ?

You can set up your own instance by downloading the latest snapshot [here](https://downloads.unidata.ucar.edu/tds/), or you can see a running instance of the latest snapshot at [thredds-test.unidata.ucar.edu](thredds-test.unidata.ucar.edu)

**Comment by PBrockmann** [comment]
Ok thank you. I will investigate. Regards

**Comment by PBrockmann** [comment]
Ok tested. Indeed it works with the tested UGRID files I had.

Just how to debug when the GetCapabilities answers 
`Cause: No grids found in underlying NetCDF dataset`

**Comment by PBrockmann** [comment]
It would be interesting to reopen this issue because I think there is some precisions to make. 
Perhaps a GitHub discussion would be better.

I have tried a UGRID found from https://psyplot.github.io/examples/maps/example_ugrid.html
The ugrid_demo.nc. The WMS GetCapacities response seems ok but there are in fact no Layers.

http://0.0.0.0/thredds/wms/testAll/ugrid_demo.nc?service=WMS&version=1.3.0&request=GetCapabilities
```
<Layer>
<Title>netCDF output from StormFlash2d</Title>
</Layer>
```

Is this file uncorrect from the UGRID convention ?
