### ISSUE TITLE
Test and improve error messages for constraint expressions in opendap

### ISSUE THREAD

**Issue by tdrwenski** [Unidata/tds#362]
The open dap spec contains a section about [constraint expressions](https://opendap.github.io/documentation/UserGuideComprehensive.html#Constraint_Expressions), which includes queries like `?var&var>0`. All types of expressions in the spec should work and be tested.

This does not currently work in TDS and is not tested either. This could be a regression, but as there are no tests or evidence that it used to work, I am labeling this as an enhancement.

**Comment by ethanrd** [comment]
A Sequence in OPeNDAP is a structure that may have many instances. So this dataset
```
Dataset {
    Int32 u;
    Int32 v;
    Sequence {
        Int32 x;
        Int32 y;
    } Point;
} vol_1_ce_1;
```
might have 100 `Points` (the size isn't known till you request and receive it). A request for `Point.x>5` would return all the `Point`s that have `x` values greater than 5, however many that might be.

**Comment by tdrwenski** [comment]
Thanks Ethan! That is clear now! The current behavior may be correct then (I have not thoroughly tested it though).

Maybe then I will revise this issue to:
- Improve the error message given when a selection operator is used on the wrong type. It should not be a 500 error like we are getting now.
- Ensure there are tests for all types of constraint expressions and data types

**Comment by DennisHeimbigner** [comment]
Good catch, Ethan. I assumed the query was against a sequence. Ethan is correct that only
sequences should support relational expressions.
