### ISSUE TITLE
Thredds 4.x -> 5.x • "Entry is too large" in catalogInit.log

### ISSUE THREAD

**Issue by enzo-pauvy** [Unidata/tds#368]
Hello there,

I am trying to deploy a dockerized Thredds based on [unidata/thredds-docker](https://hub.docker.com/r/unidata/thredds-docker/). I recently saw there were no 4.x versions anymore.
Are these old images no longer available at all? Except [archives files](https://github.com/Unidata/thredds-docker/tags)? I should ask this question on the [thredds-docker GitHub](https://github.com/Unidata/thredds-docker), but this is not my main point.
___

I had to upgrade from Thredds 4.6 to 5.4 so it was the opportunity to work on it.
But I encountered a few problems.
I reproduced the issue by deploying this new Thredds version without docker, with tomcat 9 and jdk 11.

I used an existing Thredds catalog, but reduced it to only one dataset.
On Thredds 5.4, in `catalogInit.log` after the `readCatalog()` call it print this error:

```java
*** ERROR: initializing catalog catalog.xml; ChronicleMap{name=null, file=/usr/local/apache-tomcat-9.0.75/content/thredds/cache/catalog/chronicle.datasets.dat.1, identityHashCode=2097525231}: Entry is too large: requires 6386 chunks, 4858 is maximum.
java.lang.IllegalArgumentException: ChronicleMap{name=null, file=/usr/local/apache-tomcat-9.0.75/content/thredds/cache/catalog/chronicle.datasets.dat.1, identityHashCode=2097525231}: Entry is too large: requires 6386 chunks, 4858 is maximum.
```

This implies that services are not working at all.
- OpenDAP :
```java
Error {
    code = 404;
    message = "<PRODUCT_NAME>";
};
```
- WMS : 500 Internal error

But the product page is accessible.

The dataset is pretty huge, so I tried to reduce the number of netCDF files called in the aggregation and it **worked**.

I also tried with the whole dataset on Thredds 4.6.20 and it worked as well.

I did not find any information about this issue, nor related to chunk size.
Neither is in the documentation.

Do you have any idea?

Kind regards,
Enzo

**Comment by tdrwenski** [comment]
TDS 4 was EOL last year-- it has security issues we can no longer fix.

Can you share your catalog? If I understand correctly, it has one very large aggregation in it. How many files are inolved?

**Comment by haileyajohnson** [comment]
Is it an aggregation or a feature collection? You may need to adjust the configuration of the cache (based on the ChronicleMap error you're getting). It would help if we could see your catalog and your threddsConfig.xml.

**Comment by tdrwenski** [comment]
Hi, thanks for the extra info!

What do you have for your `<maxDatasets>` in your [threddsConfig.xml](https://docs.unidata.ucar.edu/tds/current/userguide/tds_config_ref.html#configuration-catalog)? Can you share the whole `<ConfigCatalog>` part of your threddsConfig.xml?

The default is 10,000 datasets that can fit in the cache, but this is assuming 10,000 datasets with NcML strings of average length of 200 characters. If I understand your description correctly, you are using a catalog with two datasets that each have a really really large generated NcML (I am estimating based on your snippet something like 6 million characters for the one with ~80k files). The cache that is failing here is trying to cache that NcML but has allocated too little space to fit this large entry.

I have two initial suggestions:
- Maybe you can first try to extend the `maxDatasets` parameter to a much larger number and see if that helps-- this should make the cache bigger.
- You could try using a DatasetScan, which would greatly reduce the NcML size in your catalog. Are you sure that the performance is worse for that?

**Comment by enzo-pauvy** [comment]
**ConfigCatalog**

In my `<ConfigCatalog>` I tried with the highest `<maxDatasets>` value.
Define the `<keepInMemory>` making it work for the smallest datasets, but not the bigger ones.
I also tried with massive values, but it did not work.

```xml
  <ConfigCatalog>
    <keepInMemory>512000</keepInMemory>
    <maxDatasets>7000000</maxDatasets>
  </ConfigCatalog>
```

**DatasetScan**

Please tell me if I am wrong, but [datasetScan](https://docs.unidata.ucar.edu/tds/current/userguide/tds_dataset_scan_ref.html) is used for file-based access.
Here, I am looking for an aggregation of every file.

I tried to use `<scan>` into my `<aggregation>` tag.
It seemed to be ok on the `catalogInit.log` side, but took soooo long to load that I got a time-out.
Even for the smaller datasets (the already working ones) it works as well, but it is faster with my netCDF list than with `<scan>` (a few seconds).

**Memory**

> For this test, I get back on my docker version, since the problem is on both (docker and non-docker). 

At first, I was with **8Go** of container memory and **6Go** for Thredds `-Xmx`.
I tried with **15Go** of memory and **12Go** for `-Xmx`, but there was no difference.
About the "chunk" error, the maximum value in `catalogInit.log` is still the same: `47585 is maximum`.

Should I try with even more memory?
Or is there another parameter I forgot?

As a reminder, this catalog works on 4.6.x Thredds.
Isn't v5 better at resource optimization? Or not worse, at least?

**Comment by tdrwenski** [comment]
> Please tell me if I am wrong, but [datasetScan](https://docs.unidata.ucar.edu/tds/current/userguide/tds_dataset_scan_ref.html) is used for file-based access.
Here, I am looking for an aggregation of every file.
> 
> I tried to use <scan> into my <aggregation> tag.
> It seemed to be ok on the catalogInit.log side, but took soooo long to load that I got a time-out.
> Even for the smaller datasets (the already working ones) it works as well, but it is faster with my netCDF list than with <scan> (a few seconds).

Yes, you are correct! I meant an `aggregation` with a `scan` element, not a `datasetScan`. Thanks for testing that out, that is too bad that it is so slow.

I will have another look at that cache if there are anymore settings we can tune to get your situation working.

**Comment by tdrwenski** [comment]
Can you test again with the latest snapshot (which you can download [here](https://downloads.unidata.ucar.edu/tds/5.5/thredds-5.5-SNAPSHOT.war))? We increased the allocated value size for this cache. If you still get the same error, please let us know as well-- we are considering if we need to add a configuration option to allow for very large NcML values.

**Comment by enzo-pauvy** [comment]
**5.5-SNAPSHOT**

The error appears again in `catalogInit.log` on the same dataset but with different sizes of chunks.

On 5.4
```
Entry is too large: requires 123309 chunks, 47585 is maximum.
```

On 5.5
```
Entry is too large: requires 114657 chunks, 75895 is maximum.
```

**Comment by tdrwenski** [comment]
Hi, can you test with the latest snapshot again (which you can download [here](https://downloads.unidata.ucar.edu/tds/5.5/thredds-5.5-SNAPSHOT.war)). Also can you try adding the new setting we just introduced (not yet in the docs) to your config:
```
  <ConfigCatalog>
    <averageValueSize>large</averageValueSize>
  </ConfigCatalog>
  ```
The value size allocated for each dataset in the cache will be much larger with this setting. If this works correctly, then probably you can use the default setting for `maxDatasets` again (10,000).

**Comment by enzo-pauvy** [comment]
It almost worked!

There is no problem for the first +30 `readCatalog()` in `catalogInit.log`.
But then, I have again:

```
Entry is too large: requires 25429 chunks, 10591 is maximum.
```

This may be due to my test environment, here I am working locally on my machine.
You said this would increase the size **for each dataset**, but it seems to be a "global" limit.
If I remove the catalog that's causing the problem, the next one returns the same error, as if it reached a global limit. I will take a closer look next week.

Will this setting soon be added to the docker 5.5-snapshot image? ([thredds-docker](https://hub.docker.com/r/unidata/thredds-docker/tags))
If it is not yet documented, I assume it will take some time.
___

Without `<averageValueSize>` it stopped at the second catalog with:

```
Entry is too large: requires 357851 chunks, 17178 is maximum.
```

**Comment by tdrwenski** [comment]
Thanks for testing again, sorry it's not quite working.

How many datasets do you have? And can you either send a complete catalog or else can you tell me the length of the NcML in your catalog for a typical dataset (I had estimated it was 6 million characters based on the snippet you sent)?

> Will this setting soon be added to the docker 5.5-snapshot image? ([thredds-docker](https://hub.docker.com/r/unidata/thredds-docker/tags))

We have not made a new docker snapshot yet but we can release one soon if that is useful.

**Comment by enzo-pauvy** [comment]
I have 40~45 datasets.
As I said in [this comment](https://github.com/Unidata/tds/issues/368#issuecomment-1556936139), I list many netCDF files in my dataset, so my catalogs are a bit huge.
How can I measure the total NcML length?

Here are some figures (1 line = 1 dataset):
- 613943 netCDF files, ~4.3MB each
- 471478 netCDF files, ~15MB each
- 153509 netCDF files, ~10MB each
- 98581 netCDF files, ~18MB each

These datasets should be some of the biggest I have.

**Comment by tdrwenski** [comment]
Sorry for the delay in getting back to you on this issue and thanks for sending the extra info.

Maybe you have already tried this, but you can try to increase the `maxDatasets` parameter while also setting the `averageValueSize` to `large`. This will allocate even more space for your catalog cache. The default location for this cache is `${tds.content.root.path}/thredds/cache/catalog/`, so you may want to keep an eye on how large the files are there if you have limited disk space.
 
I am afraid that TDS 5.x is just not very well-equipped to handle very large NcML due to the caching library we use to store this. Maybe you can see if there are ways to limit the size of your NcML (number of characters in the `<netcdf>` xml element) per dataset entry, maybe by splitting up large datasets into smaller ones.

It would definitely be better if the  `<scan>` performed as well as listing the files explicitly, so if none of the above suggestions help, maybe you can make an issue about the scan performance (no promises that we can get to it right away though).

**Comment by enzo-pauvy** [comment]
Thank you for your time, we will keep our current version of Thredds and plan future actions on our side.
