### ISSUE TITLE
Template file tdsTemplateFragments.html is ignored

### ISSUE THREAD

**Issue by gaellafond** [Unidata/tds#390]
**TDS version**: 5.5-SNAPSHOT

**Environment**: Docker image

**Description**:

I follow the guide to customise the look and feel of THREDDS:
https://docs.unidata.ucar.edu/tds/current/userguide/customizing_tds_look_and_feel.html

No changes happen no matter what I put it the `tdsTemplateFragments.html`. I looked at TDS source code. I found where the template file is created (`tdsContext.java`), but it doesn't seems to be used anywhere in the application.

Is this feature actually working? Do I need to add a config value somewhere?

**Comment by haileyajohnson** [comment]
This is a known issue, please see #353
