### ISSUE TITLE
Ncml enhancements not applied to datasetScans

### ISSUE THREAD

**Issue by tdrwenski** [Unidata/tds#403]
While opendap does apply the ncml to its data access page, it does not apply enhancements like the standardizer when writing values as ascii when the dataset is part of a datasetScan. Related to but distinct from https://github.com/Unidata/tds/issues/398.

**Comment by DennisHeimbigner** [comment]
Should it also be applied to streamed binary data?

**Comment by tdrwenski** [comment]
yes, I think so! I just wrote ascii in the issue because I tested that (basically because it is slightly easier to test). I expect it is the same code path for both binary and ascii that had the error, I will be sure to test both.

**Comment by DennisHeimbigner** [comment]
Does this need to be applied on the server side when the data was streamed to the client,
of on the client side when the streamed data is received by the client?

**Comment by tdrwenski** [comment]
The server needs to apply the ncml enhancements when reading the data. I have actually already found the bug for this issue, its not even specific to opendap, just to any service in the TDS that is opening a NetCDF dataset in a certain way.

**Comment by DennisHeimbigner** [comment]
Presumably DAP4 will also need this fix.

**Comment by haileyajohnson** [comment]
@DennisHeimbigner I believe it will be a lower level change than the access service itself, it will be at the netcdffile level

**Comment by tdrwenski** [comment]
I think the fix I have will work for all services that go through the TDS's `DatasetManager` to open NetCDF datasets (I see cdmremote, wms, and opendap using this right now), so I don't expect any work is needed there.
