### ISSUE TITLE
Server Error (500: IOException sending File 13: Permission denied) for model data and RTMA Data not updating

### ISSUE THREAD

**Issue by edrewitz** [Unidata/tds#409]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.): 
* a description of the issue with the steps needed to reproduce it

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

Hi all!

I am trying to get the best GFS data and I started getting errors I have not seen before. I know the errors aren't in my code since it worked just the other day. I get an error that says "Server Error (500: IOException sending File 13: Permission denied)" when I try to access the data. I'm not sure why I get this error. I also noticed the RTMA data isn't updating either. I am using a Windows 10 OS, Python 3.11.4. To reproduce the issue is just by running the program. On my program that looks at the RTMA data, if I parse using the TDSCatalog using 'Latest Collection' the program runs but it pulls in old data from 12z which is the last file available and I did this after 15z this morning so the 13z is usually available. If I parse straight into the latest time using the datetime module, I get errors and it doesn't run since the file isn't there. Basically what I am trying to say is I can still access some of the data and it isn't down completely but there are some issues since it seems like I can't access fully and can only partially. 

Thanks!

Eric

**Comment by edrewitz** [comment]
One thing I will add that I didn't notice until after I posted the prior post is in the RTMA files, I saw the 12z file before but now it disappeared and it only goes out to the 11z file.

**Comment by haileyajohnson** [comment]
Thanks! We're having some issues on our data flowing to that TDS instance right now and are working to get it up to date again. In the meantime, you can try accessing the same data from thredds-test.unidata.ucar.edu, which is up to date and working correctly.

**Comment by tdrwenski** [comment]
I believe that the problem with our thredds production server is now resolved. Let us know if you still have issues!
