### ISSUE TITLE
Godiva issues with update

### ISSUE THREAD

**Issue by bsroth** [Unidata/tds#414]
Hello,

We recently upgraded to 5.4 from 4.6 and I've discovered two issues that I would like help with:

1) When using the godiva3 viewer on the preview tab it is writing all links for server= to http.  We have a proxy infront of thredds that redirects all traffic to https, the traffic is then sent on to our haproxy load balancer where the ssl is terminated and sent on to port 8080 on the application server.  An example:

https://ds.nccs.nasa.gov/thredds/Godiva.html?server=http://ds.dp.nccs.nasa.gov/thredds/wms/GMAO/GEOS-CF/forecast/Y2019/M01/D01/H12/GEOS-CF.v01.fcst.aqc_tavg_1hr_g1440x721_v1.20190101_12z+20190101_1330z.nc4

If i manually change http to https everything appears to work as expected.  Is there a way to change this behavior without putting Apache/Nginx infront of thredds or extending the ssl into tomcat?

2)We found that even if we manually change http to https on files with special characters in the name of the file.  The url is passed properly but godiva is stripping the + portion of the file name.  Is this a case of godiva not parsing the file names properly?  See above url for example.

Thanks
Brian

**Comment by mnlerman** [comment]
Hello, Thank you for reaching out! I was able to see the diferences between the file names with and without "+" on your server but I'm having a hard time understanding your question about the http and https. Can you provide more info about your work flow?

**Comment by bsroth** [comment]
We were able to fine an old issue that indicated this was a tomcat issue and the need for ssl on tomcat.  This appears to have fixed that issue.

Brian Roth
Senior Linux System Administrator
NASA Center for Climate Simulation (NCCS)
ASRC Federal InuTeq, LLC
Code 606.2, Bldg 28, Remote: Owosso,MI
Goddard Space Flight Center
Greenbelt, MD 20771


From: Megan Lerman ***@***.***>
Reply-To: Unidata/tds ***@***.***>
Date: Thursday, September 7, 2023 at 6:13 PM
To: Unidata/tds ***@***.***>
Cc: "Roth, Brian S. (GSFC-606.2)[InuTeq, LLC]" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [Unidata/tds] Godiva issues with update (Issue #414)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



Hello, Thank you for reaching out! I was able to see the diferences between the file names with and without "+" on your server but I'm having a hard time understanding your question about the http and https. Can you provide more info about your work flow?

**Comment by mnlerman** [comment]
That's great to hear, I'm glad you were able to get that worked out! 

Regarding the "+" in the file name, I think that it's likely causing problems when parsing the URL. The + symbol is the URL encoding for a space which might be the source of the error. I replaced the + with %2B which is the URL encoding for + and was able to access the data correctly with this link:
https://ds.nccs.nasa.gov/thredds/Godiva.html?server=https://ds.nccs.nasa.gov/thredds/wms/GMAO/GEOS-CF/forecast/Y2019/M01/D01/H12/GEOS-CF.v01.fcst.aqc_tavg_1hr_g1440x721_v1.20190101_12z%2B20190101_1330z.nc4

**Comment by bsroth** [comment]
Yeah I figured as much but this is not something that I can change as there are numerous data sets with this used in the file name.  The data sets are provided to thousands of researchers around the world.

Brian Roth
Senior Linux System Administrator
NASA Center for Climate Simulation (NCCS)
ASRC Federal InuTeq, LLC
Code 606.2, Bldg 28, Remote: Owosso,MI
Goddard Space Flight Center
Greenbelt, MD 20771


From: Megan Lerman ***@***.***>
Reply-To: Unidata/tds ***@***.***>
Date: Friday, September 8, 2023 at 2:01 PM
To: Unidata/tds ***@***.***>
Cc: "Roth, Brian S. (GSFC-606.2)[InuTeq, LLC]" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [Unidata/tds] Godiva issues with update (Issue #414)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



That's great to hear, I'm glad you were able to get that worked out!

Regarding the "+" in the file name, I think that it's likely causing problems when parsing the URL. The + symbol is the URL encoding for a space which might be the source of the error. I replaced the + with %2B which is the URL encoding for + and was able to access the data correctly with this link:
https://ds.nccs.nasa.gov/thredds/Godiva.html?server=https://ds.nccs.nasa.gov/thredds/wms/GMAO/GEOS-CF/forecast/Y2019/M01/D01/H12/GEOS-CF.v01.fcst.aqc_tavg_1hr_g1440x721_v1.20190101_12z%2B20190101_1330z.nc4

**Comment by mnlerman** [comment]
I did some digging and confirmed that my suspicion about the + being decoded to a space in the URL was correct. I can resolve this by encoding the file name initially when we create the URL. I'm working on a fix that should resolve this issue. It should be available soon. I'll send another update when this issue is resolved

**Comment by mnlerman** [comment]
This fix was merged into the code base last week and should be available in the latest thredds-5.5 snapshot available here: https://downloads.unidata.ucar.edu/tds/ Please reach back out if you experience any additional problems.
