### ISSUE TITLE
Unable to get stick vectors for velocity fields

### ISSUE THREAD

**Issue by jbzambon** [Unidata/tds#429]
* the version of the software with which you are encountering an issue
THREDDS v. 4.6.14

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
AWS Linux 2023.2.20231026
c3.large type instance
JDK 8u221 (1.8.0_221)
Apache Tomcat 8.5.43

* a description of the issue with the steps needed to reproduce it

Hello, I am having trouble getting stick vectors to appear for U, V fields. I [understand that in order for THREDDS to render](https://www.unidata.ucar.edu/mailing_lists/archives/thredds/2011/msg00128.html) these u, v fields as combined velocity + vector plots they need to be CF-Compliant. Specifically for sea water, they need to be u_eastward and v_northward. The U, V fields are not rotated and I cannot go back and run the model (ROMS) to get the u_eastward and v_northward fields pushed into the normal ROMS output.

As a solution, I attempted to hack the fields by copying the netcdf attributes from a dataset that has these CF-compliant fields and actually renders the combined u, v vector plots (attached this code below). This was somewhat "lazily" done as I didn't actually go through the progress of converting the u, v points to rho points (arakawa-C grid) so the dims are still `time, s_rho, eta_u, xi_u` and not `time, s_rho, eta_rho, xi_rho`. Unfortunately, this didn't "trigger" THREDDS to see these fields as vectors and only gives me u, v in WMS and not combined velocity.

Example of not-working u, v component WMS (GODIVA2)
Example of working u, v component WMS (GODIVA2) with drawn vectors

My next thought is to not-lazily convert u, v to rho and massage them into a separate file that I build from scratch (e.g. `ncgen` from the working versions CDL file with CF-compliant u_eastward, v_northward).

Any other ideas? Thanks!

-Joe

```
#!/bin/bash
#
# Program to convert u,v to u_eastward and v_northward
#  Note that this does not convert from velocity to rho points like true
#  u_eastward and v_northward
#
# Usage: convert_vars.bash [filename]
#
# Joseph B. Zambon
#  jbzambon@ncsu.edu
#  2 Nov 2023

ncatted -O -a standard_name,u,o,c,eastward_sea_water_velocity $1
ncatted -O -a long_name,u,o,c,eastward\ momentum\ component\ at\ RHO-points $1
ncatted -O -a location,u,o,c,face $1
ncatted -O -a field,u,o,c,u_eastward\,\ scalar\,\ series $1
ncrename -h -O -v u,u_eastward $1
ncatted -O -a standard_name,v,o,c,northward_sea_water_velocity $1
ncatted -O -a long_name,v,o,c,northward\ momentum\ component\ at\ RHO-points $1
ncatted -O -a location,v,o,c,face $1
ncatted -O -a field,v,o,c,v_northward\,\ scalar\,\ series $1
ncrename -h -O -v v,v_northward $1
```

**Comment by haileyajohnson** [comment]
Hi @jbzambon - the version of THREDDS that you are using is no longer supported and is not a part of this repository, it was archived [here](https://github.com/Unidata/thredds).

We currently support versions 5.4 and 5.5-SNAPSHOT of the TDS, which you can find on our [downloads page](https://downloads.unidata.ucar.edu/tds/). We have some [documentation](https://docs.unidata.ucar.edu/tds/current/userguide/upgrade.html) to help you with the upgrade to version 5.x, and are happy to help you with any problems you night encounter, either here on this repository or at [support-thredds@unidata.ucar.edu](support-thredds@unidata.ucar.edu).
