### ISSUE TITLE
IOException Instead of Validation Error/Exception for Incorrect <timeCoverage>

### ISSUE THREAD

**Issue by nathan-hook** [Unidata/tds#430]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
* a description of the issue with the steps needed to reproduce it

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

This problem happens in an older version of the tds and might not be a 'real' problem anymore.

Version: 5.0.0-beta6

To reproduce, just change a thredds dataset xml file to have a non-existent date like:
February 30th.

`
<timeCoverage>
    <start>2099-02-30T12:00:00</start>
    <end>2099-11-30T12:00:00</end>
</timeCoverage>
`

Then go view the dataset via the xml url and there will be an IOException.  A friendly reminder that an IOException implies that there is something wrong reading/writing the file to/from disk and it caused great confession when attempting to debug this problem.

It would be much clearer if there was some sort of validation exception that explains the exact problem like:

ValidationException:  timeCoverage start of '2099-02-30T12:00:00' does not exist.

Thank you for your time.

**Comment by mnlerman** [comment]
Hello, @nathan-hook, thanks for the input! While I do think that info would helpful for debugging, I don't know if anyone on our team will have the bandwidth to get to it in the near future. We are an open source project and welcome pull requests if this change is something that you feel inclined to take on.
