### ISSUE TITLE
WMS service not updating time coverage of a dataset

### ISSUE THREAD

**Issue by WeatherGod** [Unidata/tds#448]
Custom TDS build between v5.4 and v5.5-beta.

I've been investigating an issue in a webapp of mine that depends on the WMS and WCS services from thredds. It queries WMS for the date range of the datasets. If a new file is added to the dataset's directory, it would continue reporting the same date range, even after the `recheckEvery` wait period. Just figured out that the WMS and WCS services were reporting different time ranges, indicating to me that there is a bug somewhere in the WMS portion of the code that is keeping it from updating the internal state of the dataset.

To test this out, I spun up my thredds server with 13 monthly files. I then queried for both the WCS and WMS catalog information and they reported the correct information. I then copied into the directory the next month's file and waited 15 minutes and re-fetched the catalog information. Below are the relevant portions of their responses:

WMS
```
Layer queryable="1">
<Name>drought</Name>
<Title>
weighted drought index 0-4 (0: abnormally dry - 4: exceptional drought, 255: no drought)
</Title>
<Abstract>
weighted drought index 0-4 (0: abnormally dry - 4: exceptional drought, 255: no drought)
</Abstract>
<EX_GeographicBoundingBox>
<westBoundLongitude>-180.0</westBoundLongitude>
<eastBoundLongitude>179.875</eastBoundLongitude>
<southBoundLatitude>-90.0</southBoundLatitude>
<northBoundLatitude>90.0</northBoundLatitude>
</EX_GeographicBoundingBox>
<BoundingBox CRS="CRS:84" minx="-180.0" maxx="179.875" miny="-90.0" maxy="90.0"/>
<Dimension name="time" units="ISO8601" multipleValues="true" current="true" default="2023-01-01T00:00:00.000Z">
2022-01-01T00:00:00.000Z,2022-02-01T00:00:00.000Z,2022-03-01T00:00:00.000Z,2022-04-01T00:00:00.000Z,2022-05-01T00:00:00.000Z,2022-06-01T00:00:00.000Z,2022-07-01T00:00:00.000Z/2022-09-01T00:00:00.000Z/P31D,2022-10-01T00:00:00.000Z,2022-11-01T00:00:00.000Z,2022-12-01T00:00:00.000Z,2023-01-01T00:00:00.000Z
</Dimension>
<Style>
<Name>default-categorical</Name>
<Title>default-categorical</Title>
<Abstract>default-categorical style</Abstract>
</Style>
</Layer>
```

WCS
```
<CoverageOfferingBrief>
<description>
weighted drought index 0-4 (0: abnormally dry - 4: exceptional drought, 255: no drought)
</description>
<name>drought</name>
<label>
weighted drought index 0-4 (0: abnormally dry - 4: exceptional drought, 255: no drought)
</label>
<lonLatEnvelope srsName="urn:ogc:def:crs:OGC:1.3:CRS84">
<gml:pos>179.875 -90.0</gml:pos>
<gml:pos>539.875 90.0</gml:pos>
<gml:timePosition>2022-01-01T00:00:00Z</gml:timePosition>
<gml:timePosition>2023-02-01T00:00:00Z</gml:timePosition>
</lonLatEnvelope>
</CoverageOfferingBrief>
```
(just noticed that the longitude range in the WCS report is bad, too)

I'm about to go diving into the code to see if I can find the source of the problem. I have a suspicion that the WMS code is "over-caching", which I noticed back when I was investigating performance issues before. If you all have your own thoughts for the reasons, let me know.

I'll see if I can do an experiment run without my local modifications to verify that they are not the culprit (they shouldn't be because they should only impact the WCS downloads).

**Comment by tdrwenski** [comment]
There was an issue that we fixed a while back in 5.5 that WMS never updated files in its cache (https://github.com/Unidata/tds/pull/294). Please let us know if you are still having issues with the latest 5.5-SNAPSHOT and we will have a look.

**Comment by WeatherGod** [comment]
I did just confirm the bug with a stock v5.4 docker image (and the longitude thing went away, too).

With stock 5.5-SNAPSHOT, the time coverage information is still not updated (and the incorrect longitude thing is also happening).

**Comment by WeatherGod** [comment]
From what I've seen so far, comparing how the WCS and WMS services are implemented, it seems like the WCS servlet takes a very deferential approach to managing dataset objects, while WMS proactively caches them. Not exactly sure if that could be the difference, though as the dataset objects themselves (cached or not) is responsible for refreshing themselves, right?

I need to sit down with some paper and diagram this thing out...

**Comment by tdrwenski** [comment]
What does your catalog entry look like for this aggregation?

**Comment by WeatherGod** [comment]
Sorry, I never saw this reply. The catalog entry for this particular entry is a bit of a bear
```
    <netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
      <remove name="FDI" type="variable" />
      <remove name="datasets" type="attribute" />
      <remove name="history" type="attribute" />
      <remove name="land_threshold" type="attribute" />
      <variable name="drought"
        orgName="FDI_weighted"
        type="int">
        <attribute name="flag_colors" value="#FEFF9D #FFE203 #FF5B02 #D20100 #4C0000"/>
        <attribute name="flag_meanings" value="D0_-_Abnormally_Dry D1_-_Moderate_Drought D2_-_Severe_Drought D3_-_Extreme_Drought D4_-_Exceptional_Drought"/>
        <attribute name="flag_values" value="0 1 2 3 4"
          type="int"/>
        <remove name="_ChunkSizes" type="attribute" />
      </variable>
      <variable name="spei01"
        type="int">
        <attribute name="flag_colors" value="#FEFF9D #FFE203 #FF5B02 #D20100 #4C0000"/>
        <attribute name="flag_meanings" value="D0_-_Abnormally_Dry D1_-_Moderate_Drought D2_-_Severe_Drought D3_-_Extreme_Drought D4_-_Exceptional_Drought"/>
        <attribute name="flag_values" value="0 1 2 3 4"
          type="int"/>
        <remove name="_ChunkSizes" type="attribute" />
      </variable>
      <variable name="spei03"
        type="int">
        <attribute name="flag_colors" value="#FEFF9D #FFE203 #FF5B02 #D20100 #4C0000"/>
        <attribute name="flag_meanings" value="D0_-_Abnormally_Dry D1_-_Moderate_Drought D2_-_Severe_Drought D3_-_Extreme_Drought D4_-_Exceptional_Drought"/>
        <attribute name="flag_values" value="0 1 2 3 4"
          type="int"/>
        <remove name="_ChunkSizes" type="attribute" />
      </variable>
      <variable name="spei12"
        type="int">
        <attribute name="flag_colors" value="#FEFF9D #FFE203 #FF5B02 #D20100 #4C0000"/>
        <attribute name="flag_meanings" value="D0_-_Abnormally_Dry D1_-_Moderate_Drought D2_-_Severe_Drought D3_-_Extreme_Drought D4_-_Exceptional_Drought"/>
        <attribute name="flag_values" value="0 1 2 3 4"
          type="int"/>
        <remove name="_ChunkSizes" type="attribute" />
      </variable>
      <aggregation type="joinNew"
          dimName="time"
          recheckEvery="15 min">
        <variableAgg name="FDI_weighted"/>
        <variableAgg name="spei01"/>
        <variableAgg name="spei03"/>
        <variableAgg name="spei12"/>
        <scan location="/data/test/drought/"
          dateFormatMark="GDMv4_#yyyyMM"
          regExp="GDMv4_[0-9]{6}\.nc$"
          subdirs="true"/>
      </aggregation>
    </netcdf>
  </dataset>
```

**Comment by tdrwenski** [comment]
We just merged some fixes to the WMS cache. Would you mind testing again with the latest snapshot to see if the WMS issue is fixed for you?

There's a new snapshot here: https://downloads.unidata.ucar.edu/tds/5.5/thredds-5.5-SNAPSHOT.war and a new docker image for the 5.5-SNAPSHOT as well.

**Comment by WeatherGod** [comment]
Yes! It does seem to fix the problem! I'll need to study it a bit further to see if the cache behavior is still good.

The WCS's longitude thing is still happening. I'll open a new issue for that as that is something completely different.

**Comment by tdrwenski** [comment]
Great! And just so you know, we merged one more tweak to the WMS cache today and there's a new snapshot for that. There's no newer docker image but we can make that if it is useful for you.

I will close this issue. Feel free to open a new one for the WCS issue or any other WMS issues that come up.

**Comment by WeatherGod** [comment]
My cache tests yesterday went great! Stuff in the cache stayed there as expected and it picked up the new file and cached it after 15 minutes without disrupting anything else. This is great!

Any idea when v5.5 will be released (with a tagged docker image)? I'm able to rebuild my containers with my other feature patches off of the bleeding edge, but I prefer to work off of releases of netcdf-java and tds.

**Comment by haileyajohnson** [comment]
Glad to hear it's working! We don't have a set date for you yet but are working on it and appreciate your patience. Best we can say right now is:
![dog-husky](https://github.com/Unidata/tds/assets/21203790/82f853fc-9b5c-4fd6-b6bf-ac364069750e)

**Comment by tdrwenski** [comment]
Hi @WeatherGod, just a heads up that there was a WMS concurrency bug in the snapshot we told you to use here but it should be fixed in today's snapshot! Let us know if you encounter any more WMS issues.
