### ISSUE TITLE
WMS GetCapabilities XML is truncated with 5.4 but works fine with 4.6

### ISSUE THREAD

**Issue by tlvu** [Unidata/tds#449]
* the version of the software with which you are encountering an issue

Docker image 5.4 https://hub.docker.com/layers/unidata/thredds-docker/5.4/images/sha256-e55bc1cb834e44e88ee8ff55f85c46543ea9cc8a860b1e0c2d266c360dacbdd2?context=explore

* a description of the issue with the steps needed to reproduce it

On 4.6, this link works fine https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/wms/birdhouse/testdata/flyingpigeon/cmip5/tasmax_Amon_MPI-ESM-MR_rcp45_r2i1p1_200601-200612.nc?service=WMS&version=1.3.0&request=GetCapabilities

With 5.4, the XML is truncated at
```xml
        <Layer>
            <Title>Birdhouse Thredds Data Server</Title>
            <CRS>EPSG:4326</CRS>
            <CRS>CRS:84</CRS>
            <CRS>EPSG:41001</CRS>
            <CRS>EPSG:27700</CRS>
            <CRS>EPSG:3408</CRS>
            <CRS>EPSG:3409</CRS>
            <CRS>EPSG:3857</CRS>
            <CRS>EPSG:5041</CRS>
            <CRS>EPSG:5042</CRS>
            <CRS>EPSG:32661</CRS>
            <CRS>EPSG:32761</CRS>
            <Layer>
                <Title>MPI-ESM-MR model output prepared for CMIP5 RCP4.5</Title>
```

`docker logs thredds` gives `[error] Exception in macro #layer called at templates/capabilities-1.3.0.vm[line 170, column 1]` and nothing else.

Any other clues to help us diagnose?

**Comment by haileyajohnson** [comment]
Hi @tlvu please check that the schema link is correct in your wmsConfig file (it should be `https://schemas.unidata.ucar.edu/thredds/dtd/ncwms/wmsConfig.dtd`). If that does not resolve the issue, you can try to workaround suggested [here](#291 )

**Comment by tlvu** [comment]
> If that does not resolve the issue, you can try to workaround suggested [here](#291)

Corrected link https://github.com/Unidata/tds/issues/291#issuecomment-1403098258

**Comment by tlvu** [comment]
> Hi @tlvu please check that the schema link is correct in your wmsConfig file (it should be `https://schemas.unidata.ucar.edu/thredds/dtd/ncwms/wmsConfig.dtd`)

@haileyajohnson that works, thanks !
