### ISSUE TITLE
TDS' HttpHeadFilter Set Negative Content-Length Response Header for HTTP HEAD Requests

### ISSUE THREAD

**Issue by nathan-hook** [Unidata/tds#460]
TDS Version:
5.0.0-beta6, but looking at github the problem still exists with more current versions of the tds.

Problem:

In the HttpHeadFilter there is a private class (NoBodyResponseWrapper, extends HttpServletResponseWrapper) that has a setContentLength() method.  In this method the parent classes setContentLength(int length) method is called with the size of the response body content length.  If that content length is larger than the maximum value of an Integer, then the value will be wrong.

This has caused our nginx proxy to start returning 502 Bad Gateway responses because some Content-Length headers are negative.

Interestingly enough the ServletUtil seems to handle this particular use case correctly (when a file's content-length is larger than the maximum value of an Integer), but it seems as though that behavior is overridden by the HttpHeadFilter.

Here are the two classes in github...

HttpHeadFilter:
https://github.com/Unidata/tds/blob/main/dap4/d4ts/src/main/java/dap4/d4ts/HttpHeadFilter.java

ServletUtil:
https://github.com/Unidata/tds/blob/main/tds/src/main/java/thredds/servlet/ServletUtil.java

Friendly FYI, there are two places where ServletUtil sets the responses content length.  One seems to handle the above use case, the other (which is dealing with a string) does not.

Thank you for your time,

Nathan

**Comment by haileyajohnson** [comment]
What type requests are triggering this behavior?

**Comment by nathan-hook** [comment]
> What type requests are triggering this behavior?

I guess I should have added that to my initial post...

Here are some real life examples:

`$ curl -I https://tds.ucar.edu/thredds/fileServer/datazone/cordex/data/raw/NAM-22/day/CRCM5-UQAM/CanESM2/hist/tasmin/tasmin.hist.CanESM2.CRCM5-UQAM.day.NAM-22.raw.nc
HTTP/2 200
server: nginx/1.25.3
date: Tue, 23 Jan 2024 19:15:56 GMT
content-type: application/x-netcdf
content-length: 307795464
last-modified: Tue, 28 Apr 2020 20:41:46 GMT
accept-ranges: bytes`

The above files size on disk is 8897730056.

Then here is an example of a 502 Bad Gateway response due to a negative content-length:

`$ curl -I https://tds.ucar.edu/thredds/fileServer/datazone/cordex/data/mbcn-Daymet/NAM-44i/day/WRF/GFDL-ESM2M/hist/hurs/hurs.hist.GFDL-ESM2M.WRF.day.NAM-44i.mbcn-Daymet.nc
HTTP/2 502
server: nginx/1.25.3
date: Tue, 23 Jan 2024 19:14:27 GMT
content-type: text/html
content-length: 266
etag: "65985645-10a"`

That files size on disk is 3164611504.

Both these example files can be found on glade.  I can email the exact location to tds-support@ucar.edu as needed.

**Comment by tdrwenski** [comment]
Thanks for the extra info! We have tested using the fileServer and a length longer than the max int and the content length is correct in the our latest version (5.5-SNAPSHOT). The HttpHeadFilter code you point to is only used for dap4 requests and will not be hit for fileServer requests.

Do you know the admins of that TDS server (it is not maintained by Unidata though it is by another group at UCAR)? Updating to the latest TDS version should fix your issue. If you are not able to contact the admins of that server we can try to.

**Comment by nathan-hook** [comment]
That is excellent information on the content-length.

The team that I work on @ ncar are the ones that manage/run that particular tds.

We will try updating to the version you mentioned when we have time.

Thank you for all the information and for your time.

**Comment by tdrwenski** [comment]
Great! Let us know if you have any questions/ issues about the upgrade!

Here is the downloads page: https://downloads.unidata.ucar.edu/tds/
