### ISSUE TITLE
THREDDS Server Is Down 503 Error

### ISSUE THREAD

**Issue by edrewitz** [Unidata/tds#477]
Hey all!

I'm not sure if this is for scheduled server maintenance so in case it is not, I wanted to let you know that the UCAR THREDDS Server is down. Thanks!

<img width="658" alt="Error" src="https://github.com/Unidata/tds/assets/101157849/de134a80-edfb-47b3-a9b9-9ff669ee3350">

**Comment by tdrwenski** [comment]
Hi, thanks for reporting this issue! We did have an unplanned outage yesterday, but everything is working now and we are investigating the cause.

**Comment by edrewitz** [comment]
The server went down again.

**Comment by edrewitz** [comment]
Ok, now it came back online. I'll keep my comment here rather than delete it so you have record of the server hick up this weekend.

**Comment by tdrwenski** [comment]
Thanks for the heads up. Our systems team is investigating this as well!
