### ISSUE TITLE
Modifying the TDS properties

### ISSUE THREAD

**Issue by anikfal** [Unidata/tds#481]
In the file `thredds-5.4/WEB-INF/templates/commonFragments.html`, how can I change `webappName` from _THREDDS Data Server_ to some other term?

```xml
    <div th:fragment="banner" class="banner">
        <h2>Welcome to
            <th:block th:text="${webappName}"/>
             top-level TDS Catalog.
        </h2>
        <h3>Hosted by
            <a class="static" th:href="${hostInstUrl}" th:text="${hostInst}"></a>.
        </h3>
    </div>
```

It seems by modifying the line (below) in `thredds-5.4/WEB-INF/web.xml`, it is possible to change `webappName`. But how can I set a variable for that?

`<display-name>THREDDS Data Server</display-name>` 

Generally, how can I change the default values of the [TDS properties](https://docs.unidata.ucar.edu/tds/current/userguide/customizing_tds_look_and_feel.html#accessing-tds-properties-in-custom-templates)?

**Comment by haileyajohnson** [comment]
The `webappName` and `contextPath` are set in the `web.xml` file as you did above. Most of the other properties are set in `threddsConfig.xml` (see [here](https://docs.unidata.ucar.edu/tds/current/userguide/tds_config_ref.html#server-information)).

I am not sure what you mean by setting a variable for that.
