### ISSUE TITLE
Thredds Docker 5.5-SNAPSHOT does not work for NetCDF for Horizontal extent and Horizontal subset

### ISSUE THREAD

**Issue by kensinzl** [Unidata/tds#482]
I am using the Thredds docker from https://hub.docker.com/r/unidata/thredds-docker/tags, 5.5-SNAPSHOT

`FROM unidata/thredds-docker:5.5-SNAPSHOT`

I found all my NetCDF files on the Thredds server do not work correctly if I open them, eg: the **Horizontal extent** content becomes blank and **Horizontal subset** tab information with the constant latitude and longitude value. I attached the image.

![Screenshot 2024-03-19 at 11 07 31 AM](https://github.com/Unidata/thredds-docker/assets/19411085/00f463b3-6f15-40f1-ae5c-3ba84855debe)

If I degrade the image version still 5.5-SNAPSHOT, but older digest, eg: 
`FROM unidata/thredds-docker:5.5-SNAPSHOT@sha256:35a802ffda16f87b2e465182b1c3567e16ff91a3c94f2671776358751422381e`, it works fine.

![Screenshot 2024-03-19 at 11 18 47 AM](https://github.com/Unidata/thredds-docker/assets/19411085/a47e0971-9fa1-455c-96b8-317746c0aff2)

Is there something I missed? What I want to say is that the digests from late Oct 2023 to the Present do not work correctly. thanks so much.

**Comment by haileyajohnson** [comment]
@kensinzl thanks! Confirmed this is unrelate to docker and we'll be looking into fixing it on our end.
