### ISSUE TITLE
DatasetTrackerChronicle failing on k8s

### ISSUE THREAD

**Issue by WeatherGod** [Unidata/tds#484]
This may be a "me" problem rather than a thredds problem, but one way or another, I figure others may run inito this problem.

I'm testing out the latest thredds snapshot container (as of March 27th) in my k8s-based system and it is failing to initialize the catalog because it seems like it can't use fallocate on the cache directory.
```
# head content/thredds/logs/catalogInit.log 
You are currently running TDS version 5.5-SNAPSHOT - 2024-03-26T05:25:12+0000
Latest Available TDS Version Info:
    latest development version = 5.5-SNAPSHOT
    latest release version = 5.4

=========================================================================================
ConfigCatalogInitialization readMode=always isStartup=true
DatasetTrackerChronicle failed on '/usr/local/tomcat/content/thredds/cache/catalog/chronicle.datasets.dat.1', delete catalog cache and reload 
java.io.IOException: Not enough space to fallocate 8 MiB to / unallocated was 0 MiB
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.fallocate(VanillaChronicleHash.java:1123) ~[chronicle-map-3.23.5.jar:3.23.5]
...
```

This is very odd because I have `/usr/local/tomcat/content/thredds/cache` set as an `emptyDir` mounted volume with 8Gi of epemeral storage available (not that I ever needed anywhere near that much before). In v5.4, this directory would typically house ~40 or so Mi of cached data and wouldn't have any issues creating the catalog cache file:
```
# head -n 20 content/thredds/logs/catalogInit.log 
You are currently running TDS version 5.4 - 2022-07-01T12:01:49-0600
Latest Available TDS Version Info:
    latest development version = 5.5-SNAPSHOT
    latest release version = 5.4

=========================================================================================
ConfigCatalogInitialization readMode=always isStartup=true
DatasetTrackerChronicle opened success on '/usr/local/tomcat/content/thredds/cache/catalog/chronicle.datasets.dat.1'
ConfigCatalogInitializion datasetTracker database already exists - closing it before reinitialization.
ConfigCatalogInit: initializing 1 root catalogs.
Checking catalogRoot = catalog.xml
-------readCatalog(): path=catalog.xml
...
```

My best guess at what is happening is that while the cache directory is mounted as xfs (which supports fallocate), perhaps the underlying host volume does not? I'm still investigating.

**Comment by WeatherGod** [comment]
Oh, this is going to be a fun hisenbug to figure out. If I log into the pod directly and run fallocate from the command-line, it works just fine:
```
root@...:/usr/local/tomcat/content/thredds/cache# touch catalog/foobar.txt
root@...:/usr/local/tomcat/content/thredds/cache# fallocate -z -l 10M catalog/foobar.txt
root@...:/usr/local/tomcat/content/thredds/cache# ls -lh catalog/
total 11M
-rw-r----- 1 tomcat tomcat   28 Mar 27 20:13 catTracker.dat
-rw-r----- 1 tomcat tomcat 8.6M Mar 27 20:13 chronicle.datasets.dat.1
-rw-r----- 1 tomcat tomcat    0 Mar 27 20:13 datarootTracker.dat
-rw-r--r-- 1 root   root    10M Mar 28 14:54 foobar.txt
```

**Comment by tdrwenski** [comment]
Sounds similar to this issue: https://github.com/Unidata/tds/issues/384, which I'm not sure if was resolved or not because we didn't get much response, so not sure if it helps.

This reply might be useful though: https://github.com/Unidata/tds/issues/384#issuecomment-1599141995

**Comment by WeatherGod** [comment]
yeah, in the working setup as explained in that comment, the thredds content directory in its entirety is mounted on EFS. It is something to consider for myself, but I really would like to figure out why this is happening.

I modified the configs for my thredds pod to get rid of the `emptyDir`, so now the cache directory is in the overlay root volume. Yeah, I wasn't expecting this to work, just wanted to see what happens. Came across something interesting:
```
root@h2o-thredds-5f4c46f5d-7cbw5:/usr/local/tomcat# ls -lh /usr/local/tomcat/content/thredds/cache/catalog/
total 8.0K
-rw-r----- 1 tomcat tomcat   28 Mar 28 16:58 catTracker.dat
-rw-r----- 1 tomcat tomcat 8.6M Mar 28 16:58 chronicle.datasets.dat.1
-rw-r----- 1 tomcat tomcat    0 Mar 28 16:58 datarootTracker.dat
root@h2o-thredds-5f4c46f5d-7cbw5:/usr/local/tomcat# du -hsc /usr/local/tomcat/content/thredds/cache/*
0	/usr/local/tomcat/content/thredds/cache/agg
0	/usr/local/tomcat/content/thredds/cache/aggNew
8.0K	/usr/local/tomcat/content/thredds/cache/catalog
0	/usr/local/tomcat/content/thredds/cache/cdm
4.0K	/usr/local/tomcat/content/thredds/cache/collection
0	/usr/local/tomcat/content/thredds/cache/grib
0	/usr/local/tomcat/content/thredds/cache/ncss
0	/usr/local/tomcat/content/thredds/cache/wcs
12K	total
root@h2o-thredds-5f4c46f5d-7cbw5:/usr/local/tomcat# du -hsc /usr/local/tomcat/content/thredds/cache/catalog/*
4.0K	/usr/local/tomcat/content/thredds/cache/catalog/catTracker.dat
4.0K	/usr/local/tomcat/content/thredds/cache/catalog/chronicle.datasets.dat.1
0	/usr/local/tomcat/content/thredds/cache/catalog/datarootTracker.dat
8.0K	total
```
So, the `chronical.datasets.dat.1` file must be a sparse file. If I do the same thing on a v5.4 thredds deployment, the file sizes make sense. Not sure what to make of this, but it shows that there is definitely something different about how the chronical file is managed.

**Comment by WeatherGod** [comment]
According to documentation associated with chronicle-map, it seems like they are expecting volumes that "bind"-ed. Not quite sure if my emptyDir volume counts as that.

Looking further, it actually seems like the code goes through some nasty exceptions, but eventually ends up doing some sort of fallback approach and manages to move on, so this might actually be mostly a bunch of noise. If I browse to `https://hostname/thredds/`, I get an actual browsable catalog, but I can't use any of the services.

For example, trying to GetCapabilities for WCS results in this in the threddsServlet logs:
```
2024-03-28T18:01:55.621 +0000 [   3819278][     494] INFO  - threddsServlet - Remote host: 10.16.1.62 - Request: "GET /thredds/wcs/era5/monthly-anomaly.nc?service=WCS&version=1.0.0&request=GetCapabilities HTTP/1.1"
2024-03-28T18:01:55.621 +0000 [   3819278][     494] ERROR - thredds.server.wcs.WcsHandler - Unknown problem.
java.lang.NullPointerException: null
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.findResourceControl(DatasetTrackerChronicle.java:216) ~[tdcommon-5.5-SNAPSHOT.jar:5.5-SNAPSHOT]
	at thredds.core.DatasetManager.resourceControlOk(DatasetManager.java:550) ~[classes/:5.5-SNAPSHOT]
	at thredds.core.DatasetManager.openCoverageDataset(DatasetManager.java:394) ~[classes/:5.5-SNAPSHOT]
	at thredds.core.TdsRequestedDataset.openAsCoverageDataset(TdsRequestedDataset.java:149) ~[classes/:5.5-SNAPSHOT]
	at thredds.server.wcs.WcsRequestParser.parseRequest(WcsRequestParser.java:57) ~[classes/:5.5-SNAPSHOT]
	at thredds.server.wcs.WcsHandler.handleKVP(WcsHandler.java:58) [classes/:5.5-SNAPSHOT]
	at thredds.server.wcs.WCSController.doGet(WCSController.java:127) [classes/:5.5-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```

**Comment by WeatherGod** [comment]
Just noticed this in the pod's stdout/stderr at startup. Might be relevant?
```
28-Mar-2024 18:34:02.653 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for thi
s logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on net.openhft.chronicle.core.Jvm (file:/usr/local/tomcat/webapps/thredds/WEB-INF/lib/chronicle-core-2.23.36.jar) to class java.lang.reflect.
AccessibleObject
WARNING: Please consider reporting this to the maintainers of net.openhft.chronicle.core.Jvm
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

I don't regularly do java development, so I really don't understand the whole "reflective" programming stuff.

**Comment by WeatherGod** [comment]
I'm putting together a PR that will put some null checks in DatasetTrackerChronicle.java. It probably won't solve the problem, but at least error handling will be better. One thing I noticed is that if `open()` fails, the exception gets caught, logged, and then a `reinit()` is called, which basically does the same thing, except it swallows any exceptions and just returns true/false. And that return is just completely ignored. Shouldn't we rather have the DatasetTrackerChronicle constructor raise an exception? This would significantly cut back on the amount of null checks.

**Comment by WeatherGod** [comment]
I haven't yet been able to build a patched version of ChronicleMap to test out, but I have a strong suspicion that this recently accepted PR: https://github.com/OpenHFT/Chronicle-Map/pull/521 would fix the problem. Not being a java developer, I'm running into issues trying to build the jar myself, and the project's documentation is not helpful at all to me since I don't know what is and isn't relevant.

**Comment by WeatherGod** [comment]
Ok, I managed to have some success building their development branch, but that is a few minor versions ahead of what TDS is using. I'm going to see what's the oldest version of chronicle-map I can build and work from there as the patch I'm eyeing is very simple and straight-forward.

**Comment by WeatherGod** [comment]
Ah, fun... all I can build is their development branch, which seems to be marked at 3.25.7, compared against 3.23.5 that TDS is currently using. I did see the comment in netcdf-java warning about taking care when upgrading chronicle because netcdf-java and chronicle seems to need to specify specific versions of jna.

**Comment by WeatherGod** [comment]
That's understandable that you don't want to release with a dependency on an Early Access release. I do recommend at least opening a draft PR for this upgrade against the Early Access release just to shake things out. Like I said, when I tried the upgrade it myself, I ran into a bunch of hurdles, and even when I finally managed to get a build to complete, the tests were erroring in odd ways that I couldn't scrutinize. At the moment, I'm assuming it is because I have zero experience mucking around with POMs and BOMs and gradle files, but maybe there are other bugs that chronicle needs reporting.

**Comment by WeatherGod** [comment]
New release of chronicle-map: https://github.com/OpenHFT/Chronicle-Map/releases

**Comment by tdrwenski** [comment]
Thanks for the heads up on that. It looks like they released a new [bom](https://github.com/OpenHFT/OpenHFT/releases/tag/chronicle-bom-2.25.66) as well but I am not seeing it on maven [repo](https://repo.maven.apache.org/maven2/net/openhft/chronicle-bom/) yet. As soon as it is available on maven we can update the version in the TDS.

**Comment by WeatherGod** [comment]
It appears that they won't be publishing it there? I have posted a question about this to an issue. https://github.com/OpenHFT/OpenHFT/issues/174

**Comment by WeatherGod** [comment]
Looks like OpenHFT has decided that stable artifacts are to be obtained through a purchase license, which is technically allowed under the LGPL-3.0 license (it only guarantees the source code's availability). Both the released BOM and Chronicle-Map are not on maven. I'm not familiar enough with Java packaging to make any recommendation on how to proceed in the near term, but long term, it might be worth considering alternatives for whatever Chronicle-Map is even used for.

**Comment by tdrwenski** [comment]
Hi @WeatherGod, thanks for that info, I was not aware of this and it isn't that clear from their documentation. Even some of the snapshots seem to be missing from maven. I agree, this could be a reason to move away from chronicle in the long term. In the short term, we can use one of their snapshots. I have made a [PR ](https://github.com/Unidata/tds/pull/502) to upgrade to a snapshot with the fix you mentioned (chronicle map 3.25ea6)

**Comment by tdrwenski** [comment]
There is a new thredds-docker 5.5-SNAPSHOT that should have the chronicle map upgrade in it.

**Comment by WeatherGod** [comment]
I can confirm that the new snapshot works perfectly on k8s. Thank you!

**Comment by tdrwenski** [comment]
Great, thanks for testing it!
