### ISSUE TITLE
 [error] Exception in macro #layer called at templates/capabilities-1.3.0.vm[line 170, column 1]

### ISSUE THREAD

**Issue by nriet** [Unidata/tds#488]
unidata/thredds-docker:5.4

docker run --restart=always --name='thredds' -d -p 8080:8080 unidata/thredds-docker:5.4

Start without Internet, and access WMS and report error，

http://localhost:8080/thredds/wms/testAll/2004050300_eta_211.nc?service=WMS&version=1.3.0&request=GetCapabilities
<img width="2047" alt="image" src="https://github.com/Unidata/tds/assets/105616087/0a41cd12-42eb-43e6-98e7-52d685a61989">

log
 [error] Exception in macro #layer called at templates/capabilities-1.3.0.vm[line 170, column 1]

**Comment by tdrwenski** [comment]
Normally, your wmsConfig.xml file should start with the following two lines:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wmsConfig SYSTEM "https://schemas.unidata.ucar.edu/thredds/dtd/ncwms/wmsConfig.dtd">
```
but this requires internet access to get that schema file. You can also download it [here](https://schemas.unidata.ucar.edu/thredds/dtd/ncwms/wmsConfig.dtd) and the point the wmsConfig.xml to a path where you saved it on your local file system.

See also https://github.com/Unidata/tds/issues/291#issuecomment-1403098258

**Comment by nriet** [comment]
> 通常，您的 wmsConfig.xml 文件应以以下两行开头：
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE wmsConfig SYSTEM "https://schemas.unidata.ucar.edu/thredds/dtd/ncwms/wmsConfig.dtd">
> ```
> 
> 但这需要访问互联网才能获取该架构文件。您还可以[在此处](https://schemas.unidata.ucar.edu/thredds/dtd/ncwms/wmsConfig.dtd)下载它，并将 wmsConfig.xml 指向您在本地文件系统上保存它的路径。
> 
> 另请参阅[#291（评论）](https://github.com/Unidata/tds/issues/291#issuecomment-1403098258)

Yes, Thank you very much for solving my problem
