### ISSUE TITLE
RTMA Data on UCAR THREDDS Server not updating

### ISSUE THREAD

**Issue by edrewitz** [Unidata/tds#506]
Hi all, 

I noticed the latest datasets available for the RTMA Analysis on the UCAR THREDDS Server is from 6/28/2024 at 08z. Looks like the data stopped updating around that time. Thanks.

**Comment by tdrwenski** [comment]
Thanks for letting us know! The issue should be resolved now. By the way, I believe that thredds-test.unidata.ucar.edu did have the updated data, so just so you know if it happens again in the future, you can try checking there as a temporary workaround.
