### ISSUE TITLE
SSL Certificate Error RTMA Data

### ISSUE THREAD

**Issue by edrewitz** [Unidata/tds#508]
Hi all, 

I am getting an SSL certificate error when trying to access the RTMA data. However, other forms of data I am able to access fine. I am not sure how to fix this. Please see screenshot of error message. Thanks. 

Regards,

Eric
<img width="858" alt="error" src="https://github.com/Unidata/tds/assets/101157849/cbbf2a05-b64c-4d5a-86ec-9cd92427d5dd">

**Comment by tdrwenski** [comment]
Just to be sure I understand-- the above error occur when using thredds-test.unidata.ucar.edu but not when using thredds.ucar.edu?

**Comment by edrewitz** [comment]
> Just to be sure I understand-- the above error occur when using thredds-test.unidata.ucar.edu but not when using thredds.ucar.edu?

Correct.

**Comment by tdrwenski** [comment]
I can't reproduce this, both TDSes' certificates work for me with siphon. Perhaps it is an issue with the root certificates in your local python/development environment?

**Comment by tdrwenski** [comment]
There was an issue with our certificate chain that has now been resolved. Would you mind testing again with thredds-test?

**Comment by edrewitz** [comment]
> There was an issue with our certificate chain that has now been resolved. Would you mind testing again with thredds-test? Sorry for the delayed response (I was off and out of the office). I just tested this and it works for me now. Thanks for all your help! 

<img width="661" alt="Screenshot 2024-07-11 102330" src="https://github.com/Unidata/tds/assets/101157849/6268ee75-5070-4425-8a20-02151dd3ebdc">

**Comment by tdrwenski** [comment]
Thank you for testing!
