### ISSUE TITLE
HTTP HEAD requests on thredds/fileServer seem to read entire file, only to report the file size.

### ISSUE THREAD

**Issue by nathanlcarlson** [Unidata/tds#52]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue and environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
```
$ catalina.sh version
...
Server version: Apache Tomcat/8.5.39
Server built:   Mar 14 2019 11:24:26 UTC
Server number:  8.5.39.0
OS Name:        Linux
OS Version:     3.10.0-1062.1.1.el7.x86_64
Architecture:   amd64
JVM Version:    1.8.0_222-b10
JVM Vendor:     Oracle Corporation
...
$ uname -a
Linux [hostname] 3.10.0-1062.1.1.el7.x86_64 #1 SMP Tue Aug 13 18:39:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ cat thredds/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: THREDDS Data Server (TDS)
Implementation-Version: 5.0.0-beta5
Built-By: @lesserwhirls lesserwhirls
Implementation-Vendor-Id: edu.ucar
Implementation-URL: https://www.unidata.ucar.edu/software/thredds/curr
 ent/tds/TDS.html
Created-By: Gradle 3.5.1
Build-Jdk: 1.8.0_171
Built-On: 2018-09-10T18:14:26-0600
Implementation-Vendor: UCAR/Unidata
```

* a description of the issue with the steps needed to reproduce it

Performing an HTTP HEAD request on `thredds/fileServer` seem to read the entire file, just to report its size. Is this intentional? It can place significant load on the server.

Looking around a little, it looks like this may be the relevant code:

https://github.com/Unidata/tds/blob/v5.0.0-beta7/tds/src/main/java/thredds/servlet/filter/HttpHeadFilter.java

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Comment by nathanlcarlson** [comment]
Reading around a bit, I understand this a little bit better. It looks like this is the expected behavior for a HEAD request, to pretend it is a GET request, but not actually return the content. It seems like an efficiency improvement could be made that simply checks the file size rather than actually reading the file contents, since that is what will be returned. I do not know the technical details of doing such a thing in Java, or if it is exactly possible, but may be worth while.

**Comment by lesserwhirls** [comment]
Thank you for the report @nathanlcarlson! This does seem very inefficient. No need to increase the I/O burden on an already I/O bound application :-)

I think we could edit [tds/src/main/webapp/WEB-INF/applicationContext.xml](https://github.com/Unidata/tds/blob/d6d520d616365ce2be44851a0181baca690c194a/tds/src/main/webapp/WEB-INF/applicationContext.xml#L40-L44) to add a filter specific to `fileServer` requests that uses the does not include the `HttpHeadFilter`. Then, we could use the Spring `RequestMapping` annotation in the [FileServerController](https://github.com/Unidata/tds/blob/master/tds/src/main/java/thredds/server/fileserver/FileServerController.java) to differentiate between the GET and HEAD requests behavior.

It seems like starting with Spring 4.3, any controller annotated for GET requests are implicitly used for HEAD requests (if a HEAD specific request mapping does not exists). To me, that means we would not need the `HttpHeadFilter` at all if we moved all of our controllers over to use Spring `RequestMapping` annotations. That's a slightly larger chunk of work, but migrating the `FileServerController` over would be a nice first step.
