### ISSUE TITLE
Question: how to download netcdf from aggregate

### ISSUE THREAD

**Issue by fullergalway** [Unidata/tds#67]
Hi,

I've been struggling to figure out how to get a netcdf download from an aggregate, given an ascii or dods url:
http://thredds.marine.ie/thredds/dodsC/IMI_CMEMS/AGGREGATE.ascii?lon[0:1:1],lat[0:1:1],v[0:1:1][0:1:1][0:1:1],time[0:1:1],u[0:1:1][0:1:1][0:1:1]

Thanks for any tips???!!!
Rob Fuller

**Comment by lesserwhirls** [comment]
Greetings!

There are a few ways to download a netCDF file based on an opendap end point from a TDS. If you have netCDF-C installed with dap capabilities enabled, you could use nccopy like so:

~~~bash
nccopy "http://thredds.marine.ie/thredds/dodsC/IMI_CMEMS/AGGREGATE?lon[0:1:864],lat[0:1:1080],v[0:1:0][0:1:0][0:1:0]" local_file.nc
~~~

which will result in a local file called `local_file.nc`. Here I've just removed the `.ascii` ending of the path of the url in your question. Note that you might need to replace the `[` characters with `%5B`, and the `]` characters with `%5D` in some cases depending on the server and version of netCDF-C being used (as the `[` and `]` characters technically should be percent encoded).

Another option would be to use `ncks` from the [NCO package](http://nco.sourceforge.net/nco.html#ncks-netCDF-Kitchen-Sink). There are others as well, but those two should get you pointed in the right direction.

Cheers!

**Comment by fullergalway** [comment]
Perfect thanks so much Sean!
