### ISSUE TITLE
Add JSON response for WMS GetFeatureInfo request

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/tds#82]
For WMS `GetFeatureInfo`, in addition to `text/xml` it would be great to add `application/json` so that requests like this would work:
http://thredds.ucar.edu/thredds/wms/grib/NCEP/WW3/Global/Best?time=2015-06-29T12%3A00%3A00.000Z&colorscalerange=0.28%2C5.53&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=Significant_height_of_combined_wind_waves_and_swell_surface&query_layers=Significant_height_of_combined_wind_waves_and_swell_surface&srs=EPSG%3A3857&bbox=-6887893.4928338025%2C5009377.085697312%2C-6261721.357121639%2C5635549.221409475&x=35&y=102&width=256&height=256&info_format=application%2Fjson
This would allow applications built with [TerriaJS](https://github.com/TerriaJS/terriajs), like [Australia's National Map](http://nationalmap.gov.au/) (and hopefully in the future the US Data.gov viewer) to work out of the box. 

Maybe an approach like this could make it easy?
http://stackoverflow.com/questions/1823264/quickest-way-to-convert-xml-to-json-in-java/1823328#1823328

Geoserver WMS `GetFeatureInfo` has supported JSON on `GetFeatureInfo` for more than 2 years -- we should catch up so that WMS services from THREDDS and Geoserver are interoperable with respect to web applications!
http://docs.geoserver.org/stable/en/user/services/wms/reference.html#getfeatureinfo

**Comment by lesserwhirls** [comment]
I'm doing some work on the ncwms (2.x) / TDS integration trying to wrap up remaining tasks for the TDS 5.0 release, and now have it setup to be able to return CoverageJSON from the wms service. Will be available in the next (and hopefully final) beta of TDS 5.
